=== dubrsl/tolven/trunk/org.tolven.assembler.pluginframework/build/classes/org/tolven/plugin/registry/xml/tpf.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns="urn:tolven-org:tpf:1.0" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:tpf="urn:tolven-org:tpf:1.0" targetNamespace="urn:tolven-org:tpf:1.0" elementFormDefault="qualified" attributeFormDefault="unqualified">

	<xs:element name="plugin">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="doc" minOccurs="0" maxOccurs="1" />
				<xs:element ref="attributes" minOccurs="0" maxOccurs="1" />
				<xs:element ref="requires" minOccurs="0" maxOccurs="1" />
				<xs:element ref="runtime" minOccurs="0" maxOccurs="1" />
				<xs:choice minOccurs="0" maxOccurs="unbounded">
					<xs:element ref="extension-point" />
					<xs:element ref="extension" />
				</xs:choice>
			</xs:sequence>
			<xs:attribute name="id" type="xs:string" use="required" />
			<xs:attribute name="version" type="xs:string" use="required" />
			<xs:attribute name="vendor" type="xs:string" />
			<xs:attribute name="class" type="xs:string" />
			<xs:attribute name="docs-path" type="xs:string" />
		</xs:complexType>
	</xs:element>

	<xs:element name="plugin-fragment">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="doc" minOccurs="0" maxOccurs="1" />
				<xs:element ref="attributes" minOccurs="0" maxOccurs="1" />
				<xs:element ref="requires" minOccurs="0" maxOccurs="1" />
				<xs:element ref="runtime" minOccurs="0" maxOccurs="1" />
				<xs:choice minOccurs="0" maxOccurs="unbounded">
					<xs:element ref="extension-point" />
					<xs:element ref="extension" />
				</xs:choice>
			</xs:sequence>
			<xs:attribute name="id" type="xs:string" use="required" />
			<xs:attribute name="version" type="xs:string" use="required" />
			<xs:attribute name="vendor" type="xs:string" />
			<xs:attribute name="plugin-id" type="xs:string" use="required" />
			<xs:attribute name="plugin-version" type="xs:string" />
			<xs:attribute name="match" default="compatible">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:enumeration value="equal" />
						<xs:enumeration value="equivalent" />
						<xs:enumeration value="compatible" />
						<xs:enumeration value="greater-or-equal" />
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="docs-path" type="xs:string" />
		</xs:complexType>
	</xs:element>

	<xs:element name="attributes">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="attribute" maxOccurs="unbounded" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>

	<xs:element name="attribute">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="doc" minOccurs="0" maxOccurs="1" />
				<xs:element ref="attribute" minOccurs="0" maxOccurs="unbounded" />
			</xs:sequence>
			<xs:attribute name="id" type="xs:string" use="required" />
			<xs:attribute name="value" type="xs:string" />
		</xs:complexType>
	</xs:element>

	<xs:element name="doc">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="doc-ref" minOccurs="0" maxOccurs="unbounded" />
				<xs:element ref="doc-text" minOccurs="0" maxOccurs="1" />
			</xs:sequence>
			<xs:attribute name="caption" type="xs:string" />
		</xs:complexType>
	</xs:element>

	<xs:element name="doc-ref">
		<xs:complexType>
			<xs:attribute name="path" type="xs:string" use="required" />
			<xs:attribute name="caption" type="xs:string" use="required" />
		</xs:complexType>
	</xs:element>

	<xs:element name="doc-text">
		<xs:complexType mixed="true" />
	</xs:element>

	<xs:element name="requires">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="import" maxOccurs="unbounded" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>

	<xs:element name="import">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="doc" minOccurs="0" maxOccurs="1" />
			</xs:sequence>
			<xs:attribute name="id" type="xs:string" />
			<xs:attribute name="plugin-id" type="xs:string" use="required" />
			<xs:attribute name="plugin-version" type="xs:string" />
			<xs:attribute name="match" default="compatible">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:enumeration value="equal" />
						<xs:enumeration value="equivalent" />
						<xs:enumeration value="compatible" />
						<xs:enumeration value="greater-or-equal" />
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="exported" default="false">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:enumeration value="true" />
						<xs:enumeration value="false" />
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="optional" default="false">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:enumeration value="true" />
						<xs:enumeration value="false" />
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="reverse-lookup" default="false">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:enumeration value="true" />
						<xs:enumeration value="false" />
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
		</xs:complexType>
	</xs:element>

	<xs:element name="runtime">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="library" maxOccurs="unbounded" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>

	<xs:element name="library">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="doc" minOccurs="0" maxOccurs="1" />
				<xs:element ref="export" minOccurs="0" maxOccurs="unbounded" />
			</xs:sequence>
			<xs:attribute name="id" type="xs:string" use="required" />
			<xs:attribute name="path" type="xs:string" use="required" />
			<xs:attribute name="type" use="required">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:enumeration value="code" />
						<xs:enumeration value="resources" />
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="version" type="xs:string" />
		</xs:complexType>
	</xs:element>

	<xs:element name="export">
		<xs:complexType>
			<xs:attribute name="prefix" type="xs:string" use="required" />
		</xs:complexType>
	</xs:element>

	<xs:element name="extension-point">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="doc" minOccurs="0" maxOccurs="1" />
				<xs:element ref="parameter-def" minOccurs="0" maxOccurs="unbounded" />
			</xs:sequence>
			<xs:attribute name="id" type="xs:string" use="required" />
			<xs:attribute name="parent-plugin-id" type="xs:string" />
			<xs:attribute name="parent-point-id" type="xs:string" />
			<xs:attribute name="extension-multiplicity" default="any">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:enumeration value="any" />
						<xs:enumeration value="one" />
						<xs:enumeration value="one-per-plugin" />
						<xs:enumeration value="none" />
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
		</xs:complexType>
	</xs:element>

	<xs:element name="parameter-def">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="doc" minOccurs="0" maxOccurs="1" />
				<xs:element ref="parameter-def" minOccurs="0" maxOccurs="unbounded" />
			</xs:sequence>
			<xs:attribute name="id" type="xs:string" use="required" />
			<xs:attribute name="multiplicity">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:enumeration value="one" />
						<xs:enumeration value="any" />
						<xs:enumeration value="none-or-one" />
						<xs:enumeration value="one-or-more" />
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="type">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:enumeration value="string" />
						<xs:enumeration value="boolean" />
						<xs:enumeration value="number" />
						<xs:enumeration value="date" />
						<xs:enumeration value="time" />
						<xs:enumeration value="date-time" />
						<xs:enumeration value="null" />
						<xs:enumeration value="any" />
						<xs:enumeration value="plugin-id" />
						<xs:enumeration value="extension-point-id" />
						<xs:enumeration value="extension-id" />
						<xs:enumeration value="fixed" />
						<xs:enumeration value="resource" />
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="custom-data" type="xs:string" use="optional" />
			<xs:attribute name="default-value" type="xs:string" use="optional" />
		</xs:complexType>
	</xs:element>

	<xs:element name="extension">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="doc" minOccurs="0" maxOccurs="1" />
				<xs:element ref="parameter" minOccurs="0" maxOccurs="unbounded" />
			</xs:sequence>
			<xs:attribute name="plugin-id" type="xs:string" use="required" />
			<xs:attribute name="point-id" type="xs:string" use="required" />
			<xs:attribute name="id" type="xs:string" use="required" />
		</xs:complexType>
	</xs:element>

	<xs:element name="parameter">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="doc" minOccurs="0" maxOccurs="1" />
				<xs:element ref="parameter" minOccurs="0" maxOccurs="unbounded" />
			</xs:sequence>
			<xs:attribute name="id" type="xs:string" use="required" />
			<xs:attribute name="value" type="xs:string" use="optional" />
		</xs:complexType>
	</xs:element>

	<xs:element name="value">
		<xs:complexType mixed="true" />
	</xs:element>

</xs:schema>

=== dubrsl/tolven/org.tolven.analysis.influenza/manifest/tolven-plugin.xml
<?xml version="1.0" encoding="UTF-8"?>
<plugin id="org.tolven.analysis.influenza" version="2.1.0" vendor="Tolven" xmlns="urn:tolven-org:tpf:1.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="urn:tolven-org:tpf:1.0 http://tolven.org/xsd/tpf.xsd">
	<requires>
		<import plugin-id="org.tolven.component.application" />
		<import plugin-id="org.tolven.component.tolvenweb" />
		<import plugin-id="org.tolven.component.tolvenlocale" />
		<import plugin-id="org.tolven.component.war" />
		<import plugin-id="org.tolven.component.faces" />
		<import plugin-id="org.tolven.component.tolvenejb" />
		<import plugin-id="org.tolven.analysis" />
	</requires>
	<extension id="applications" plugin-id="org.tolven.component.application" point-id="applications">
		<parameter id="dir" value="app" />
	</extension>
	<extension id="rules" plugin-id="org.tolven.component.application" point-id="rules">
		<parameter id="dir" value="app/rules" />
	</extension>
	<extension id="fiveDirectory" plugin-id="org.tolven.component.tolvenweb" point-id="fiveDirectory">
		<parameter id="sourceDirectory" value="web/five" />
	</extension>
	<extension id="manageDirectory" plugin-id="org.tolven.component.tolvenweb" point-id="manageDirectory">
		<parameter id="sourceDirectory" value="web/manage" />
	</extension>
	<extension id="locale-en-application-locale" plugin-id="org.tolven.component.tolvenlocale" point-id="application-locale">
		<parameter id="application-name" value="echr" />
		<parameter id="properties-file" value="locale_en/echr/AppBundle_en.properties" />
	</extension>
	<extension id="ejbclasses" plugin-id="org.tolven.component.tolvenejb" point-id="classes">
		<parameter id="dir" value="ejb/classes" />
	</extension>
	<extension id="org.tolven.cohort.inflnz-property" plugin-id="org.tolven.component.tolvenejb" point-id="property">
		<parameter id="class" value="org.tolven.analysis.bean.SnapshotBean" />
		<parameter id="name" value="org.tolven.cohort.inflnz" />
		<parameter id="value" value="java:global/tolven/tolvenEJB/AnalysisChartBean!org.tolven.analysis.CohortSnapshotLocal" />
	</extension>
	<extension id="org.tolven.cohort.inflnz-navigation-rule-contribution" plugin-id="org.tolven.component.faces" point-id="navigation-rule-contribution">
		<parameter id="from-view-id" value="/manage/analysis/analysisAdmin.xhtml" />
		<parameter id="navigation-case">
			<parameter id="from-action" value="#{top.navAction}" />
			<parameter id="from-outcome" value="org.tolven.cohort.inflnz" />
			<parameter id="to-view-id" value="/manage/analysis/inflnzAnalysisAdmin.xhtml" />
		</parameter>
		<parameter id="target-plugin-id" value="org.tolven.component.tolvenweb" />
	</extension>
	<extension id="org.tolven.cohort.inflnz.inflnzvccnsnapshot-navigation-rule-contribution" plugin-id="org.tolven.component.faces" point-id="navigation-rule-contribution">
		<parameter id="from-view-id" value="/manage/analysis/analysisAdmin.xhtml" />
		<parameter id="navigation-case">
			<parameter id="from-action" value="#{top.navAction}" />
			<parameter id="from-outcome" value="org.tolven.cohort.inflnz.inflnzvccnsnapshot" />
			<parameter id="to-view-id" value="/manage/analysis/inflnzinflnzvccnAnalysisAdmin.xhtml" />
		</parameter>
		<parameter id="target-plugin-id" value="org.tolven.component.tolvenweb" />
	</extension>
</plugin>

=== dubrsl/tolven/trunk/org.tolven.deploy.glassfish3/manifest/tolven-plugin.xml
<?xml version="1.0" encoding="UTF-8"?>
<plugin id="org.tolven.deploy.glassfish3" version="2.1.0" class="org.tolven.deploy.glassfish3.GlassFish3Deploy" vendor="Tolven" xmlns="urn:tolven-org:tpf:1.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="urn:tolven-org:tpf:1.0 http://tolven.org/xsd/tpf.xsd">
	<attributes>
		<attribute id="deployDir" value="glassfish/domains/tolven/autodeploy" />
		<attribute id="binDir" value="bin" />
	</attributes>
	<requires>
		<import plugin-id="org.tolven.deploy" />
		<import plugin-id="org.tolven.jndi" />
	</requires>
	<runtime>
		<library id="tpfclasses" path="tpf/classes/" type="code" />
	</runtime>
	<extension-point id="devLib" extension-multiplicity="none">
		<parameter-def id="jar" default-value="devLib.jar" />
	</extension-point>
	<extension id="execute" plugin-id="org.tolven.deploy" point-id="execute">
		<parameter id="args" value="" />
	</extension>
	<extension-point id="tolvenJndi" extension-multiplicity="none" parent-point-id="runtimeLib" parent-plugin-id="org.tolven.jndi">
		<parameter-def multiplicity="none-or-one" id="tolvenJndi" />
	</extension-point>
</plugin>

=== dubrsl/tolven/org.tolven.mqkeystore/manifest/tolven-plugin.xml
<?xml version="1.0" encoding="UTF-8"?>
<plugin id="org.tolven.mqkeystore" version="2.0.2" vendor="Tolven" xmlns="urn:tolven-org:tpf:1.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="urn:tolven-org:tpf:1.0 http://tolven.org/xsd/tpf.xsd">
	<requires>
		<import plugin-id="org.tolven.component.tolvenejb" />
		<import plugin-id="org.tolven.config.appserver" />
		<import plugin-id="org.tolven.component.rar" />
	</requires>
	<extension-point id="devLib" extension-multiplicity="none">
		<parameter-def id="jar" default-value="devLib.jar" />
	</extension-point>
	<extension id="libJar" plugin-id="org.tolven.config.appserver" point-id="libJar">
		<parameter id="jar" value="mqKeyStore-api.jar" />
	</extension>
	<extension id="rar" plugin-id="org.tolven.component.rar" point-id="rar">
		<parameter id="rar" value="mqKeyStore.rar" />
	</extension>
	<extension id="raClasses" plugin-id="org.tolven.component.tolvenejb" point-id="classes">
		<parameter id="dir" value="ejb/classes" />
	</extension>
</plugin>

=== dubrsl/tolven/trunk/tolvenPlugin/org.tolven.config.postgresqlcredentials/tolven-plugin.xml
<?xml version="1.0" encoding="UTF-8"?>
<plugin id="org.tolven.config.postgresqlcredentials" version="2.0.1" vendor="Tolven" xmlns="urn:tolven-org:tpf:1.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="urn:tolven-org:tpf:1.0 http://tolven.org/xsd/tpf.xsd">
	<requires>
		<import plugin-id="org.tolven.assembler.admin" />
	</requires>
	<extension id="database" plugin-id="org.tolven.assembler.admin" point-id="database">
		<parameter id="database.groupId" value="#{pluginProperty['database.groupId']}" />
		<parameter id="database.rootPasswordId" value="#{pluginProperty['database.rootPasswordId']}" />
		<parameter id="databaseSSL.passwordProtected" value="#{pluginProperty['databaseSSL.passwordProtected']}" />
		<parameter id="key">
			<parameter id="databaseSSL.keyFile" value="#{pluginProperty['databaseSSL.keyFile']}" />
			<parameter id="databaseSSL.certFile" value="#{pluginProperty['databaseSSL.certFile']}" />
			<parameter id="databaseSSL.keyType" value="#{pluginProperty['databaseSSL.keyType']}" />
		</parameter>
		<parameter id="databaseSSL.trustStoreFile" value="#{pluginProperty['databaseSSL.trustStoreFile']}" />
		<parameter id="databaseSSL.trustStoreType" value="#{pluginProperty['databaseSSL.trustStoreType']}" />
		<parameter id="databaseSSL.trusted.groups" value="#{pluginProperty['databaseSSL.trusted.groups']}" />
		<parameter id="database.credentialDir" value="#{pluginProperty['database.credentialDir']}" />
	</extension>
</plugin>

=== dubrsl/tolven/trunk/org.tolven.gatekeeper.config/manifest/tolven-plugin.xml
<?xml version="1.0" encoding="UTF-8"?>
<plugin id="org.tolven.gatekeeper.config" version="2.1.0" vendor="Tolven" xmlns="urn:tolven-org:tpf:1.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="urn:tolven-org:tpf:1.0 http://tolven.org/xsd/tpf.xsd">
	<requires>
		<import plugin-id="org.tolven.gatekeeper" />
	</requires>
	
	<!-- LOCAL Resources -->
	<extension-point id="shiro-ini" extension-multiplicity="none">
		<parameter-def id="jar" default-value="shiro-ini.jar" multiplicity="none-or-one" />
	</extension-point>
	<!-- LOCAL Resources End -->
	
	<!-- LIB Extensions -->
	<extension id="shiro-ini" plugin-id="org.tolven.gatekeeper" point-id="libProduct-adaptor">
		<parameter id="source-plugin-id" value="org.tolven.gatekeeper.config" />
		<parameter id="extension-point" value="shiro-ini" />
	</extension>
	<!-- LIB Extensions End -->
	
</plugin>

=== dubrsl/tolven/trunk/org.tolven.assembler.connectormodule/manifest/tolven-plugin.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<plugin id="org.tolven.assembler.connectormodule" version="2.1.0" class="org.tolven.assembler.connectormodule.ConnectorModuleAssembler" vendor="Tolven" xsi:schemaLocation="urn:tolven-org:tpf:1.0 http://tolven.org/xsd/tpf.xsd" xmlns="urn:tolven-org:tpf:1.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
	<requires>
		<import plugin-id="org.tolven.component.rar" />
	</requires>
	<runtime>
		<library type="code" path="tpf/classes/" id="classes" />
	</runtime>
	<extension-point extension-multiplicity="none" id="devLib">
		<parameter-def default-value="devLib.jar" id="jar" />
	</extension-point>
	<extension-point id="abstractRAR" parent-plugin-id="org.tolven.component.rar" parent-point-id="abstractRAR" extension-multiplicity="none" />
</plugin>

=== dubrsl/tolven/trunk/org.tolven.deploy.substancemanufacturer/manifest/tolven-plugin.xml
<?xml version="1.0" encoding="UTF-8"?>
<plugin xmlns="urn:tolven-org:tpf:1.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="urn:tolven-org:tpf:1.0 http://tolven.org/xsd/tpf.xsd"
	id="org.tolven.deploy.substancemanufacturer" version="2.1.0" vendor="Tolven" class="org.tolven.deploy.SubstanceManufacturers.LoaderSubstanceManufacturers">
<requires>
    <import plugin-id="org.tolven.library.application" />
</requires>
<runtime>
	
	<library id="classes" path="tpf/classes/" type="code">
                <export prefix="*" />
        </library>
</runtime>

<extension-point id="devLib" extension-multiplicity="none">
	<parameter-def id="jar" default-value="devLib.jar" />
</extension-point>

</plugin>

=== dubrsl/tolven/trunk/org.tolven.deploy.breastproblems/manifest/tolven-plugin.xml
<?xml version="1.0" encoding="UTF-8"?>
<plugin id="org.tolven.deploy.breastproblems" version="2.1.0" class="org.tolven.deploy.breastproblems.LoaderBreastProblems" vendor="Tolven" xmlns="urn:tolven-org:tpf:1.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="urn:tolven-org:tpf:1.0 http://tolven.org/xsd/tpf.xsd">
	<requires>
		<import plugin-id="org.tolven.library.application" />
	</requires>
	<runtime>
		<library id="classes" path="tpf/classes/" type="code">
			<export prefix="*" />
		</library>
	</runtime>
	<extension-point id="devLib" extension-multiplicity="none">
		<parameter-def id="jar" default-value="devLib.jar" />
	</extension-point>
</plugin>
