=== dubrsl/tolven/trunk/org.tolven.assembler.pluginframework/build/classes/org/tolven/plugin/registry/xml/tpf.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns="urn:tolven-org:tpf:1.0" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:tpf="urn:tolven-org:tpf:1.0" targetNamespace="urn:tolven-org:tpf:1.0" elementFormDefault="qualified" attributeFormDefault="unqualified">

	<xs:element name="plugin">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="doc" minOccurs="0" maxOccurs="1" />
				<xs:element ref="attributes" minOccurs="0" maxOccurs="1" />
				<xs:element ref="requires" minOccurs="0" maxOccurs="1" />
				<xs:element ref="runtime" minOccurs="0" maxOccurs="1" />
				<xs:choice minOccurs="0" maxOccurs="unbounded">
					<xs:element ref="extension-point" />
					<xs:element ref="extension" />
				</xs:choice>
			</xs:sequence>
			<xs:attribute name="id" type="xs:string" use="required" />
			<xs:attribute name="version" type="xs:string" use="required" />
			<xs:attribute name="vendor" type="xs:string" />
			<xs:attribute name="class" type="xs:string" />
			<xs:attribute name="docs-path" type="xs:string" />
		</xs:complexType>
	</xs:element>

	<xs:element name="plugin-fragment">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="doc" minOccurs="0" maxOccurs="1" />
				<xs:element ref="attributes" minOccurs="0" maxOccurs="1" />
				<xs:element ref="requires" minOccurs="0" maxOccurs="1" />
				<xs:element ref="runtime" minOccurs="0" maxOccurs="1" />
				<xs:choice minOccurs="0" maxOccurs="unbounded">
					<xs:element ref="extension-point" />
					<xs:element ref="extension" />
				</xs:choice>
			</xs:sequence>
			<xs:attribute name="id" type="xs:string" use="required" />
			<xs:attribute name="version" type="xs:string" use="required" />
			<xs:attribute name="vendor" type="xs:string" />
			<xs:attribute name="plugin-id" type="xs:string" use="required" />
			<xs:attribute name="plugin-version" type="xs:string" />
			<xs:attribute name="match" default="compatible">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:enumeration value="equal" />
						<xs:enumeration value="equivalent" />
						<xs:enumeration value="compatible" />
						<xs:enumeration value="greater-or-equal" />
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="docs-path" type="xs:string" />
		</xs:complexType>
	</xs:element>

	<xs:element name="attributes">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="attribute" maxOccurs="unbounded" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>

	<xs:element name="attribute">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="doc" minOccurs="0" maxOccurs="1" />
				<xs:element ref="attribute" minOccurs="0" maxOccurs="unbounded" />
			</xs:sequence>
			<xs:attribute name="id" type="xs:string" use="required" />
			<xs:attribute name="value" type="xs:string" />
		</xs:complexType>
	</xs:element>

	<xs:element name="doc">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="doc-ref" minOccurs="0" maxOccurs="unbounded" />
				<xs:element ref="doc-text" minOccurs="0" maxOccurs="1" />
			</xs:sequence>
			<xs:attribute name="caption" type="xs:string" />
		</xs:complexType>
	</xs:element>

	<xs:element name="doc-ref">
		<xs:complexType>
			<xs:attribute name="path" type="xs:string" use="required" />
			<xs:attribute name="caption" type="xs:string" use="required" />
		</xs:complexType>
	</xs:element>

	<xs:element name="doc-text">
		<xs:complexType mixed="true" />
	</xs:element>

	<xs:element name="requires">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="import" maxOccurs="unbounded" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>

	<xs:element name="import">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="doc" minOccurs="0" maxOccurs="1" />
			</xs:sequence>
			<xs:attribute name="id" type="xs:string" />
			<xs:attribute name="plugin-id" type="xs:string" use="required" />
			<xs:attribute name="plugin-version" type="xs:string" />
			<xs:attribute name="match" default="compatible">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:enumeration value="equal" />
						<xs:enumeration value="equivalent" />
						<xs:enumeration value="compatible" />
						<xs:enumeration value="greater-or-equal" />
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="exported" default="false">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:enumeration value="true" />
						<xs:enumeration value="false" />
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="optional" default="false">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:enumeration value="true" />
						<xs:enumeration value="false" />
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="reverse-lookup" default="false">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:enumeration value="true" />
						<xs:enumeration value="false" />
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
		</xs:complexType>
	</xs:element>

	<xs:element name="runtime">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="library" maxOccurs="unbounded" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>

	<xs:element name="library">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="doc" minOccurs="0" maxOccurs="1" />
				<xs:element ref="export" minOccurs="0" maxOccurs="unbounded" />
			</xs:sequence>
			<xs:attribute name="id" type="xs:string" use="required" />
			<xs:attribute name="path" type="xs:string" use="required" />
			<xs:attribute name="type" use="required">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:enumeration value="code" />
						<xs:enumeration value="resources" />
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="version" type="xs:string" />
		</xs:complexType>
	</xs:element>

	<xs:element name="export">
		<xs:complexType>
			<xs:attribute name="prefix" type="xs:string" use="required" />
		</xs:complexType>
	</xs:element>

	<xs:element name="extension-point">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="doc" minOccurs="0" maxOccurs="1" />
				<xs:element ref="parameter-def" minOccurs="0" maxOccurs="unbounded" />
			</xs:sequence>
			<xs:attribute name="id" type="xs:string" use="required" />
			<xs:attribute name="parent-plugin-id" type="xs:string" />
			<xs:attribute name="parent-point-id" type="xs:string" />
			<xs:attribute name="extension-multiplicity" default="any">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:enumeration value="any" />
						<xs:enumeration value="one" />
						<xs:enumeration value="one-per-plugin" />
						<xs:enumeration value="none" />
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
		</xs:complexType>
	</xs:element>

	<xs:element name="parameter-def">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="doc" minOccurs="0" maxOccurs="1" />
				<xs:element ref="parameter-def" minOccurs="0" maxOccurs="unbounded" />
			</xs:sequence>
			<xs:attribute name="id" type="xs:string" use="required" />
			<xs:attribute name="multiplicity">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:enumeration value="one" />
						<xs:enumeration value="any" />
						<xs:enumeration value="none-or-one" />
						<xs:enumeration value="one-or-more" />
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="type">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:enumeration value="string" />
						<xs:enumeration value="boolean" />
						<xs:enumeration value="number" />
						<xs:enumeration value="date" />
						<xs:enumeration value="time" />
						<xs:enumeration value="date-time" />
						<xs:enumeration value="null" />
						<xs:enumeration value="any" />
						<xs:enumeration value="plugin-id" />
						<xs:enumeration value="extension-point-id" />
						<xs:enumeration value="extension-id" />
						<xs:enumeration value="fixed" />
						<xs:enumeration value="resource" />
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="custom-data" type="xs:string" use="optional" />
			<xs:attribute name="default-value" type="xs:string" use="optional" />
		</xs:complexType>
	</xs:element>

	<xs:element name="extension">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="doc" minOccurs="0" maxOccurs="1" />
				<xs:element ref="parameter" minOccurs="0" maxOccurs="unbounded" />
			</xs:sequence>
			<xs:attribute name="plugin-id" type="xs:string" use="required" />
			<xs:attribute name="point-id" type="xs:string" use="required" />
			<xs:attribute name="id" type="xs:string" use="required" />
		</xs:complexType>
	</xs:element>

	<xs:element name="parameter">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="doc" minOccurs="0" maxOccurs="1" />
				<xs:element ref="parameter" minOccurs="0" maxOccurs="unbounded" />
			</xs:sequence>
			<xs:attribute name="id" type="xs:string" use="required" />
			<xs:attribute name="value" type="xs:string" use="optional" />
		</xs:complexType>
	</xs:element>

	<xs:element name="value">
		<xs:complexType mixed="true" />
	</xs:element>

</xs:schema>

=== dubrsl/tolven/trunk/org.tolven.assembler.ear/manifest/tolven-plugin.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<plugin id="org.tolven.assembler.ear" version="2.0.12" vendor="Tolven"  class="org.tolven.assembler.ear.EARAssembler" xsi:schemaLocation="urn:tolven-org:tpf:1.0 http://tolven.org/xsd/tpf.xsd" xmlns="urn:tolven-org:tpf:1.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
	<attributes>
		<attribute value="template-application.xml" id="template-applicationxml" />
	</attributes>
	<requires>
		<import plugin-id="org.tolven.assembler.localemodule" />
		<import plugin-id="org.tolven.assembler.javamodule" />
		<import plugin-id="org.tolven.assembler.connectormodule" />
		<import plugin-id="org.tolven.assembler.ejbmodule" />
		<import plugin-id="org.tolven.assembler.war" />
	</requires>
	<runtime>
		<library type="code" path="tpf/classes/" id="classes" />
	</runtime>
	<extension-point extension-multiplicity="none" id="devLib">
		<parameter-def default-value="devLib.jar" id="jar" />
	</extension-point>
	<extension-point id="abstractEAR" parent-plugin-id="org.tolven.component.ear" parent-point-id="abstractEAR" extension-multiplicity="none" />
</plugin>

=== dubrsl/tolven/tolvenPlugin/org.tolven.component.tomcatserver/tolven-plugin.xml
<?xml version="1.0" encoding="UTF-8"?>
<plugin id="org.tolven.component.tomcatserver" version="0.0.1" vendor="Tolven" xmlns="urn:tolven-org:tpf:1.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="urn:tolven-org:tpf:1.0 http://tolven.org/xsd/tpf.xsd">
	<extension-point id="tomcatserverxmlAssembly" extension-multiplicity="one">
		<parameter-def id="connectorDefinition" default-value="connector" multiplicity="none-or-one" />
		<parameter-def id="webserverCredentialDirectory" default-value="#{pluginProperty['webserver.credentialDir']}" multiplicity="none-or-one" />
		<parameter-def id="webserverDeploymentDirectory" default-value="#{pluginProperty['webserver.deploymentDir']}" multiplicity="none-or-one" />
	</extension-point>
	<extension-point id="connector">
		<parameter-def id="port" multiplicity="none-or-one" />
		<parameter-def id="address" multiplicity="none-or-one" />
		<parameter-def id="maxThreads" multiplicity="none-or-one" />
		<parameter-def id="maxHttpHeaderSize" multiplicity="none-or-one" />
		<parameter-def id="emptySessionPath" multiplicity="none-or-one" />
		<parameter-def id="protocol" multiplicity="none-or-one" />
		<parameter-def id="enableLookups" multiplicity="none-or-one" />
		<parameter-def id="redirectPort" multiplicity="none-or-one" />
		<parameter-def id="acceptCount" multiplicity="none-or-one" />
		<parameter-def id="connectionTimeout" multiplicity="none-or-one" />
		<parameter-def id="disableUploadTimeout" multiplicity="none-or-one" />
		<parameter-def id="SSLEnabled" multiplicity="none-or-one" />
		<parameter-def id="scheme" multiplicity="none-or-one" />
		<parameter-def id="secure" multiplicity="none-or-one" />
		<parameter-def id="clientAuth" multiplicity="none-or-one" />
		<parameter-def id="sslProtocol" multiplicity="none-or-one" />
		<parameter-def id="keystoreFile" multiplicity="none-or-one" />
		<parameter-def id="keystoreType" multiplicity="none-or-one" />
		<parameter-def id="keystorePass" multiplicity="none-or-one" />
	</extension-point>
</plugin>

=== dubrsl/tolven/org.tolven.cchit.progressnotes/manifest/tolven-plugin.xml
<?xml version="1.0" encoding="UTF-8"?>
<plugin xmlns="urn:tolven-org:tpf:1.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="urn:tolven-org:tpf:1.0 http://tolven.org/xsd/tpf.xsd"
	id="org.tolven.cchit.progressnotes" version="2.1.0" vendor="Tolven">
	
	<requires>
	     <import plugin-id="org.tolven.component.tolvenejb" />
	     <import plugin-id="org.tolven.component.tolvenweb" />
		 <import plugin-id="org.tolven.component.application" />
		 <import plugin-id="org.tolven.component.war" />
		 <import plugin-id="org.tolven.component.tolvenear" />
		 <import plugin-id="org.tolven.component.tolvenweb.taglibs.trim" />		 
	</requires>

	<extension-point id="devLib" extension-multiplicity="none">
		<parameter-def id="jar" default-value="devLib.jar" />
	</extension-point>

	<extension id="applications" plugin-id="org.tolven.component.application" point-id="applications">
		<parameter id="dir" value="app" />
	</extension>
	<extension id="trims" plugin-id="org.tolven.component.application" point-id="trims">
		<parameter id="dir" value="app/trim" />
	</extension>
	
	<extension id="ejbclasses" plugin-id="org.tolven.component.tolvenejb" point-id="classes">
		<parameter id="dir" value="ejb/classes" />
	</extension>
	
	<extension id="ajaxDirectory" plugin-id="org.tolven.component.tolvenweb" point-id="ajaxDirectory">
	     <parameter id="sourceDirectory" value="web/ajax" />
	</extension>
	<extension id="drilldownDirectory" plugin-id="org.tolven.component.tolvenweb" point-id="drilldownDirectory">
	     <parameter id="sourceDirectory" value="web/drilldown" />
	</extension>
	<extension id="fiveDirectory" plugin-id="org.tolven.component.tolvenweb" point-id="fiveDirectory">
	     <parameter id="sourceDirectory" value="web/five" />
	</extension>
	<extension id="imagesDirectory" plugin-id="org.tolven.component.tolvenweb" point-id="imagesDirectory">
	     <parameter id="sourceDirectory" value="web/images" />
	</extension>
	<extension id="invitationDirectory" plugin-id="org.tolven.component.tolvenweb" point-id="invitationDirectory">
	     <parameter id="sourceDirectory" value="web/invitation" />
	</extension>
	<extension id="manageDirectory" plugin-id="org.tolven.component.tolvenweb" point-id="manageDirectory">
	     <parameter id="sourceDirectory" value="web/manage" />
	</extension>
	<extension id="privateDirectory" plugin-id="org.tolven.component.tolvenweb" point-id="privateDirectory">
	     <parameter id="sourceDirectory" value="web/private" />
	</extension>
	<extension id="publicDirectory" plugin-id="org.tolven.component.tolvenweb" point-id="publicDirectory">
	     <parameter id="sourceDirectory" value="web/public" />
	</extension>
	<extension id="scriptsDirectory" plugin-id="org.tolven.component.tolvenweb" point-id="scriptsDirectory">
	     <parameter id="sourceDirectory" value="web/scripts" />
	</extension>
	<extension id="stylesDirectory" plugin-id="org.tolven.component.tolvenweb" point-id="stylesDirectory">
	     <parameter id="sourceDirectory" value="web/styles" />
	</extension>
	<extension id="templatesDirectory" plugin-id="org.tolven.component.tolvenweb" point-id="templatesDirectory">
	     <parameter id="sourceDirectory" value="web/templates" />
	</extension>
	<extension id="wizardDirectory" plugin-id="org.tolven.component.tolvenweb" point-id="wizardDirectory">
	     <parameter id="sourceDirectory" value="web/wizard" />
	</extension>
	<extension id="progressNoteJavaScript" plugin-id="org.tolven.component.tolvenweb" point-id="portalScriptInclude">
		<parameter id="includeFile" value="scriptInclude/progressNoteScript.txt" />
	</extension>
	<extension id="tagSourceDirectory.trim" plugin-id="org.tolven.component.tolvenweb.taglibs.trim" point-id="tagSourceDirectory">
		<parameter id="source-directory" value="web/tags/trim" />
	</extension>
	
	<extension id="ProgressNoteWizardServlet" plugin-id="org.tolven.component.war" point-id="servlet">
		<parameter id="servlet-name" value="ProgressNoteWizardServlet" />
		<parameter id="servlet-class" value="org.tolven.ajax.ProgressNoteWizardServlet" />
		<parameter id="web-resource-name" value="Protected Area" />
		<parameter id="transaction" value="true" />
		<parameter id="load-on-startup" value="5" />
		<parameter id="target-plugin-id" value="org.tolven.component.tolvenweb" />
	</extension>
	<extension id="ProgressNoteWizardServletMapping" plugin-id="org.tolven.component.war" point-id="servlet-mapping-contribution">
		<parameter id="servlet-name" value="ProgressNoteWizardServlet" />
  		<parameter id="url-pattern" value="*.pnotes" />
  		<parameter id="target-plugin-id" value="org.tolven.component.tolvenweb" />
 	</extension>
	<extension id="warclasses" plugin-id="org.tolven.component.war" point-id="classes">
		<parameter id="dir" value="web/classes" />
		<parameter id="target-plugin-id" value="org.tolven.component.tolvenweb" />
	</extension>
</plugin>

=== dubrsl/tolven/trunk/org.tolven.assembler.localemodule/manifest/tolven-plugin.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<plugin id="org.tolven.assembler.localemodule" version="2.1.0" class="org.tolven.assembler.localemodule.LocaleModuleAssembler" vendor="Tolven" xsi:schemaLocation="urn:tolven-org:tpf:1.0 http://tolven.org/xsd/tpf.xsd" xmlns="urn:tolven-org:tpf:1.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
	<runtime>
		<library type="code" path="tpf/classes/" id="classes" />
	</runtime>
	<extension-point extension-multiplicity="none" id="devLib">
		<parameter-def default-value="devLib.jar" id="jar" />
	</extension-point>
	<extension-point id="component">
		<parameter-def multiplicity="none-or-one" id="language-code" />
		<parameter-def id="jar" />
		<parameter-def id="target-plugin-id" />
	</extension-point>
</plugin>

=== dubrsl/tolven/org.tolven.api.schemas/manifest/tolven-plugin.xml
<?xml version="1.0" encoding="UTF-8"?>
<plugin id="org.tolven.api.schemas" version="2.1.0" vendor="Tolven Inc" xmlns="urn:tolven-org:tpf:1.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="urn:tolven-org:tpf:1.0 http://tolven.org/xsd/tpf.xsd">
	<requires>
		<import plugin-id="org.tolven.component.war" />
		<import plugin-id="org.tolven.component.tolvenweb" />
		<import plugin-id="org.tolven.component.library" />
		<import plugin-id="org.tolven.component.tolvenear" />
	</requires>
	<extension-point id="devLib" extension-multiplicity="none">
		<parameter-def id="jar" default-value="devLib.jar" />
	</extension-point>
	<extension id="warclasses" plugin-id="org.tolven.component.war" point-id="classes">
		<parameter id="dir" value="web/classes" />
		<parameter id="target-plugin-id" value="org.tolven.component.tolvenweb" />
	</extension>
	<extension id="org.tolven.component.library.api-schemas.jar" plugin-id="org.tolven.component.library" point-id="lib">
		<parameter id="lib" value="api-schemas.jar" />
	</extension>
	<extension id="org.tolven.component.tolvenear.api-schemas.jar" plugin-id="org.tolven.component.tolvenear" point-id="javaModuleProduct">
		<parameter id="jar" value="api-schemas.jar" />
	</extension>
</plugin>

=== dubrsl/tolven/trunk/org.tolven.assembler.jboss6/manifest/tolven-plugin.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<plugin id="org.tolven.assembler.jboss6" version="2.1.0" class="org.tolven.assembler.jboss6.JBoss6Assembler" vendor="Tolven" xsi:schemaLocation="urn:tolven-org:tpf:1.0 http://tolven.org/xsd/tpf.xsd" xmlns="urn:tolven-org:tpf:1.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
	<attributes>
		<attribute id="libDir" value="server/tolven/lib" />
		<attribute id="configDir" value="server/tolven/conf" />
		<attribute id="deployDir" value="server/tolven/deploy" />
	</attributes>
	<requires>
		<import plugin-id="org.tolven.assembler" />
		<import plugin-id="org.tolven.assembler.ear" />
		<import plugin-id="org.tolven.library.tolvencommon" />
		<import plugin-id="org.tolven.config.appserver" />
		<import plugin-id="org.tolven.jndi" />
	</requires>
	<runtime>
		<library type="code" path="tpf/classes/" id="tpfclasses/" />
	</runtime>
	<extension-point extension-multiplicity="none" id="devLib">
		<parameter-def default-value="devLib.jar" id="jar" />
	</extension-point>
	<extension id="execute" plugin-id="org.tolven.assembler" point-id="execute">
		<parameter id="args" value="" />
	</extension>
	<extension-point id="tolvenJndi" extension-multiplicity="none" parent-point-id="runtimeLib" parent-plugin-id="org.tolven.jndi">
		<parameter-def multiplicity="none-or-one" id="tolvenJndi" />
	</extension-point>
	<extension-point extension-multiplicity="one" id="databasePlugin" />
	<extension-point id="libProduct-adaptor" parent-plugin-id="org.tolven.config.appserver" parent-point-id="libProduct-adaptor" extension-multiplicity="none" />
	<extension-point id="config" parent-plugin-id="org.tolven.config.appserver" parent-point-id="config" />
	<extension-point id="deploy" parent-plugin-id="org.tolven.config.appserver" parent-point-id="deploy" />
	<extension-point id="classes">
		<parameter-def id="dir" />
	</extension-point>

	<!-- LOCAL RESOURCES -->
	<extension-point id="jersey-server-jars">
		<parameter-def id="asm" default-value="jersey/asm-3.1.jar" />
		<parameter-def id="jersey-core" default-value="jersey/jersey-core-1.3.jar" />
		<parameter-def id="jersey-multipart" default-value="jersey/jersey-multipart-1.3.jar" />
		<parameter-def id="jersey-server" default-value="jersey/jersey-server-1.3.jar" />
		<parameter-def id="jsr311-api" default-value="jersey/jsr311-api-1.1.jar" />
		<parameter-def id="jersey-client" default-value="jersey/jersey-client-1.3.jar" />
		<parameter-def id="mimepull" default-value="jersey/mimepull-1.3.jar" />
	</extension-point>
	<extension-point id="metro-jars">
		<parameter-def id="asm" default-value="metro/webservices-rt.jar" />
	</extension-point>
	<!-- LOCAL RESOURCES End -->

	<extension id="libProduct-adaptor-tolvenJndi" plugin-id="org.tolven.config.appserver" point-id="libProduct-adaptor">
		<parameter id="source-plugin-id" value="org.tolven.jndi" />
		<parameter id="extension-point" value="tolvenJndi" />
	</extension>
	<extension id="libProduct-adaptor-jersey-server-jars" plugin-id="org.tolven.config.appserver" point-id="libProduct-adaptor">
		<parameter id="source-plugin-id" value="org.tolven.assembler.jboss6" />
		<parameter id="extension-point" value="jersey-server-jars" />
	</extension>
	<extension id="libProduct-adaptor-metro-jars" plugin-id="org.tolven.config.appserver" point-id="libProduct-adaptor">
		<parameter id="source-plugin-id" value="org.tolven.assembler.jboss6" />
		<parameter id="extension-point" value="metro-jars" />
	</extension>
	<extension id="deploy-tolven-jndi-service.xml" plugin-id="org.tolven.config.appserver" point-id="deploy">
		<!--<parameter id="file" value="tolven-jndi-service.xml" />-->
		<parameter id="file" value="tolven-ldap-service.xml" />
	</extension>
	<extension id="deploy-tolven-tolven-jndi-schemas" plugin-id="org.tolven.config.appserver" point-id="deploy">
		<parameter id="dir" value="tolven-jndi-schemas" />
	</extension>
	<extension id="deploy-tolven-tolven-hornetq" plugin-id="org.tolven.config.appserver" point-id="deploy">
		<parameter id="dir" value="hornetq" />
	</extension>
</plugin>

=== dubrsl/tolven/org.tolven.hl7/manifest/tolven-plugin.xml
<?xml version="1.0" encoding="UTF-8"?>
<plugin xmlns="urn:tolven-org:tpf:1.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="urn:tolven-org:tpf:1.0 http://tolven.org/xsd/tpf.xsd"
	id="org.tolven.hl7" version="2.1.1" vendor="Tolven" 
	class="HelloWorld">

<requires>
     <import plugin-id="org.tolven.component.tolvenejb" />
     <import plugin-id="org.tolven.component.tolvenweb" />
	 <import plugin-id="org.tolven.component.application" />
	 <import plugin-id="org.tolven.component.war" />
	 <import plugin-id="org.tolven.component.tolvenlocale_en" />
	 <import plugin-id="org.tolven.component.tolvenlocale" />
	 <import plugin-id="org.tolven.component.faces" />	
	 <import plugin-id="org.tolven.component.tolvenear" />
</requires>

<extension-point id="devLib" extension-multiplicity="none">
	<parameter-def id="jar" default-value="devLib.jar" />
</extension-point>

  
<extension id="applications" plugin-id="org.tolven.component.application" point-id="applications">
	<parameter id="dir" value="app" />
</extension>

<extension id="trims" plugin-id="org.tolven.component.application" point-id="trims">
	<parameter id="dir" value="app/trim" />
</extension>

<extension id="drilldownDirectory" plugin-id="org.tolven.component.tolvenweb" point-id="drilldownDirectory">
     <parameter id="sourceDirectory" value="web/drilldown" />
</extension>
 
<extension id="scriptsDirectory" plugin-id="org.tolven.component.tolvenweb" point-id="scriptsDirectory">
     <parameter id="sourceDirectory" value="web/scripts" />
</extension>

<extension id="wizardDirectory" plugin-id="org.tolven.component.tolvenweb" point-id="wizardDirectory">
     <parameter id="sourceDirectory" value="web/wizard" />
</extension>

<extension id="application-locale-echr" plugin-id="org.tolven.component.tolvenlocale" point-id="application-locale">
        <parameter id="application-name" value="echr"></parameter>
		<parameter value="hl7Locale.properties" id="properties-file" />
</extension>
 
<extension id="hl7JavaScript" plugin-id="org.tolven.component.tolvenweb" point-id="portalScriptInclude">
	<parameter id="includeFile" value="scriptInclude/hl7Scripts.txt" />
</extension>	

<extension id="warclasses" plugin-id="org.tolven.component.war" point-id="classes">
	<parameter id="dir" value="web/classes" />
	<parameter id="target-plugin-id" value="org.tolven.component.tolvenweb" />
</extension>
<extension id="ejbclasses" plugin-id="org.tolven.component.tolvenejb" point-id="classes">
     <parameter id="dir" value="ejb/classes" />
</extension>	
<extension id="hl7Jars" plugin-id="org.tolven.component.tolvenear" point-id="javaModuleProduct">
	<parameter id="dir" value="ejb/lib" />
</extension> 

<extension id="HL7AjaxServlet" plugin-id="org.tolven.component.war" point-id="servlet">
	<parameter id="servlet-name" value="HL7AjaxServlet" />
	<parameter id="servlet-class" value="org.tolven.ajax.HL7Servlet" />
	<parameter id="web-resource-name" value="Protected Area" />
	<parameter id="transaction" value="true" />
	<parameter id="load-on-startup" value="5" />
	<parameter id="target-plugin-id" value="org.tolven.component.tolvenweb" />
</extension>
<extension id="HL7AjaxServletMapping" plugin-id="org.tolven.component.war" point-id="servlet-mapping-contribution">
	<parameter id="servlet-name" value="HL7AjaxServlet" />
 		<parameter id="url-pattern" value="*.ajaxhl7" />
 		<parameter id="target-plugin-id" value="org.tolven.component.tolvenweb" />
	</extension>
</plugin>
