=== dubrsl/tolven/trunk/org.tolven.assembler.pluginframework/build/classes/org/tolven/plugin/registry/xml/tpf.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns="urn:tolven-org:tpf:1.0" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:tpf="urn:tolven-org:tpf:1.0" targetNamespace="urn:tolven-org:tpf:1.0" elementFormDefault="qualified" attributeFormDefault="unqualified">

	<xs:element name="plugin">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="doc" minOccurs="0" maxOccurs="1" />
				<xs:element ref="attributes" minOccurs="0" maxOccurs="1" />
				<xs:element ref="requires" minOccurs="0" maxOccurs="1" />
				<xs:element ref="runtime" minOccurs="0" maxOccurs="1" />
				<xs:choice minOccurs="0" maxOccurs="unbounded">
					<xs:element ref="extension-point" />
					<xs:element ref="extension" />
				</xs:choice>
			</xs:sequence>
			<xs:attribute name="id" type="xs:string" use="required" />
			<xs:attribute name="version" type="xs:string" use="required" />
			<xs:attribute name="vendor" type="xs:string" />
			<xs:attribute name="class" type="xs:string" />
			<xs:attribute name="docs-path" type="xs:string" />
		</xs:complexType>
	</xs:element>

	<xs:element name="plugin-fragment">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="doc" minOccurs="0" maxOccurs="1" />
				<xs:element ref="attributes" minOccurs="0" maxOccurs="1" />
				<xs:element ref="requires" minOccurs="0" maxOccurs="1" />
				<xs:element ref="runtime" minOccurs="0" maxOccurs="1" />
				<xs:choice minOccurs="0" maxOccurs="unbounded">
					<xs:element ref="extension-point" />
					<xs:element ref="extension" />
				</xs:choice>
			</xs:sequence>
			<xs:attribute name="id" type="xs:string" use="required" />
			<xs:attribute name="version" type="xs:string" use="required" />
			<xs:attribute name="vendor" type="xs:string" />
			<xs:attribute name="plugin-id" type="xs:string" use="required" />
			<xs:attribute name="plugin-version" type="xs:string" />
			<xs:attribute name="match" default="compatible">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:enumeration value="equal" />
						<xs:enumeration value="equivalent" />
						<xs:enumeration value="compatible" />
						<xs:enumeration value="greater-or-equal" />
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="docs-path" type="xs:string" />
		</xs:complexType>
	</xs:element>

	<xs:element name="attributes">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="attribute" maxOccurs="unbounded" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>

	<xs:element name="attribute">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="doc" minOccurs="0" maxOccurs="1" />
				<xs:element ref="attribute" minOccurs="0" maxOccurs="unbounded" />
			</xs:sequence>
			<xs:attribute name="id" type="xs:string" use="required" />
			<xs:attribute name="value" type="xs:string" />
		</xs:complexType>
	</xs:element>

	<xs:element name="doc">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="doc-ref" minOccurs="0" maxOccurs="unbounded" />
				<xs:element ref="doc-text" minOccurs="0" maxOccurs="1" />
			</xs:sequence>
			<xs:attribute name="caption" type="xs:string" />
		</xs:complexType>
	</xs:element>

	<xs:element name="doc-ref">
		<xs:complexType>
			<xs:attribute name="path" type="xs:string" use="required" />
			<xs:attribute name="caption" type="xs:string" use="required" />
		</xs:complexType>
	</xs:element>

	<xs:element name="doc-text">
		<xs:complexType mixed="true" />
	</xs:element>

	<xs:element name="requires">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="import" maxOccurs="unbounded" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>

	<xs:element name="import">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="doc" minOccurs="0" maxOccurs="1" />
			</xs:sequence>
			<xs:attribute name="id" type="xs:string" />
			<xs:attribute name="plugin-id" type="xs:string" use="required" />
			<xs:attribute name="plugin-version" type="xs:string" />
			<xs:attribute name="match" default="compatible">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:enumeration value="equal" />
						<xs:enumeration value="equivalent" />
						<xs:enumeration value="compatible" />
						<xs:enumeration value="greater-or-equal" />
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="exported" default="false">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:enumeration value="true" />
						<xs:enumeration value="false" />
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="optional" default="false">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:enumeration value="true" />
						<xs:enumeration value="false" />
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="reverse-lookup" default="false">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:enumeration value="true" />
						<xs:enumeration value="false" />
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
		</xs:complexType>
	</xs:element>

	<xs:element name="runtime">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="library" maxOccurs="unbounded" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>

	<xs:element name="library">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="doc" minOccurs="0" maxOccurs="1" />
				<xs:element ref="export" minOccurs="0" maxOccurs="unbounded" />
			</xs:sequence>
			<xs:attribute name="id" type="xs:string" use="required" />
			<xs:attribute name="path" type="xs:string" use="required" />
			<xs:attribute name="type" use="required">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:enumeration value="code" />
						<xs:enumeration value="resources" />
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="version" type="xs:string" />
		</xs:complexType>
	</xs:element>

	<xs:element name="export">
		<xs:complexType>
			<xs:attribute name="prefix" type="xs:string" use="required" />
		</xs:complexType>
	</xs:element>

	<xs:element name="extension-point">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="doc" minOccurs="0" maxOccurs="1" />
				<xs:element ref="parameter-def" minOccurs="0" maxOccurs="unbounded" />
			</xs:sequence>
			<xs:attribute name="id" type="xs:string" use="required" />
			<xs:attribute name="parent-plugin-id" type="xs:string" />
			<xs:attribute name="parent-point-id" type="xs:string" />
			<xs:attribute name="extension-multiplicity" default="any">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:enumeration value="any" />
						<xs:enumeration value="one" />
						<xs:enumeration value="one-per-plugin" />
						<xs:enumeration value="none" />
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
		</xs:complexType>
	</xs:element>

	<xs:element name="parameter-def">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="doc" minOccurs="0" maxOccurs="1" />
				<xs:element ref="parameter-def" minOccurs="0" maxOccurs="unbounded" />
			</xs:sequence>
			<xs:attribute name="id" type="xs:string" use="required" />
			<xs:attribute name="multiplicity">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:enumeration value="one" />
						<xs:enumeration value="any" />
						<xs:enumeration value="none-or-one" />
						<xs:enumeration value="one-or-more" />
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="type">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:enumeration value="string" />
						<xs:enumeration value="boolean" />
						<xs:enumeration value="number" />
						<xs:enumeration value="date" />
						<xs:enumeration value="time" />
						<xs:enumeration value="date-time" />
						<xs:enumeration value="null" />
						<xs:enumeration value="any" />
						<xs:enumeration value="plugin-id" />
						<xs:enumeration value="extension-point-id" />
						<xs:enumeration value="extension-id" />
						<xs:enumeration value="fixed" />
						<xs:enumeration value="resource" />
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="custom-data" type="xs:string" use="optional" />
			<xs:attribute name="default-value" type="xs:string" use="optional" />
		</xs:complexType>
	</xs:element>

	<xs:element name="extension">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="doc" minOccurs="0" maxOccurs="1" />
				<xs:element ref="parameter" minOccurs="0" maxOccurs="unbounded" />
			</xs:sequence>
			<xs:attribute name="plugin-id" type="xs:string" use="required" />
			<xs:attribute name="point-id" type="xs:string" use="required" />
			<xs:attribute name="id" type="xs:string" use="required" />
		</xs:complexType>
	</xs:element>

	<xs:element name="parameter">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="doc" minOccurs="0" maxOccurs="1" />
				<xs:element ref="parameter" minOccurs="0" maxOccurs="unbounded" />
			</xs:sequence>
			<xs:attribute name="id" type="xs:string" use="required" />
			<xs:attribute name="value" type="xs:string" use="optional" />
		</xs:complexType>
	</xs:element>

	<xs:element name="value">
		<xs:complexType mixed="true" />
	</xs:element>

</xs:schema>

=== dubrsl/tolven/org.tolven.deploy.reportablediagnosisLoader/manifest/tolven-plugin.xml
<?xml version="1.0" encoding="UTF-8"?>
<plugin xmlns="urn:tolven-org:tpf:1.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="urn:tolven-org:tpf:1.0 http://tolven.org/xsd/tpf.xsd"
	id="org.tolven.deploy.reportablediagnosisLoader" version="2.1.0" vendor="Tolven" 
	class="org.tolven.deploy.reportablediagnosisLoader.LoaderReportableDiagnosis">
<!-- 
	Some plugins include code that actually runs in the TPF (client) environment. For example, the assemblers and loaders contribute code that runs
	in TPF. HelloWorld, is a small example of such code.
	Other plugins are passive in TPF, supplying components to be used in, for example, building the Tolven application server.
	To create an active TPF function, include the full name of a class (see HelloWorld) in the plugin element above. 
	For a passive plugin, completely remove the class attribute from the plugin element above, remove the runtime element and its contents below, 
	and remove the HelloWorld.java from tpf/source folder. 
-->
<!-- 
	Any plugin mentioned in extensions below will need declaration in the requires element. 
	The most common plugins are already included. Add additional plugins as needed. 
-->
<requires>
     <import plugin-id="org.tolven.component.tolvenejb" />
     <import plugin-id="org.tolven.component.tolvenweb" />
	 <import plugin-id="org.tolven.component.application" />
	 <import plugin-id="org.tolven.library.application" />
</requires>
<!-- 
	Include the following only if you have code that runs in TPF itself. 
-->
<runtime>
	<library id="classes" path="tpf/classes/" type="code">
		<export prefix="*" />
	</library>
</runtime>

<!-- 
	In most case, you plugin will be included in the development library which will allow
	others to compile and debug against your code.
-->
<extension-point id="devLib" extension-multiplicity="none">
	<parameter-def id="jar" default-value="devLib.jar" />
</extension-point>

<!-- 
    Uncomment this extension to activate the application folder containing *.application.xml, *.drl, trims and reports.
	Also, be sure your build file includes the /app section
    
<extension id="applications" plugin-id="org.tolven.component.application" point-id="applications">
	<parameter id="dir" value="app" />
</extension>
-->

<!-- 
	tolvenWeb components, uncomment those sections that have content
	Also, be sure your build file includes the /web section
-->
<!--
Files with the same folder and name as corresponding files in core tolven will override core tolven files
<extension id="ajaxDirectory" plugin-id="org.tolven.component.tolvenweb" point-id="ajaxDirectory">
     <parameter id="sourceDirectory" value="web/ajax" />
</extension>
<extension id="drilldownDirectory" plugin-id="org.tolven.component.tolvenweb" point-id="drilldownDirectory">
     <parameter id="sourceDirectory" value="web/drilldown" />
</extension>
<extension id="fiveDirectory" plugin-id="org.tolven.component.tolvenweb" point-id="fiveDirectory">
     <parameter id="sourceDirectory" value="web/five" />
</extension>
<extension id="imagesDirectory" plugin-id="org.tolven.component.tolvenweb" point-id="imagesDirectory">
     <parameter id="sourceDirectory" value="web/images" />
</extension>
<extension id="invitationDirectory" plugin-id="org.tolven.component.tolvenweb" point-id="invitationDirectory">
     <parameter id="sourceDirectory" value="web/invitation" />
</extension>
<extension id="manageDirectory" plugin-id="org.tolven.component.tolvenweb" point-id="manageDirectory">
     <parameter id="sourceDirectory" value="web/manage" />
</extension>
<extension id="privateDirectory" plugin-id="org.tolven.component.tolvenweb" point-id="privateDirectory">
     <parameter id="sourceDirectory" value="web/private" />
</extension>
<extension id="publicDirectory" plugin-id="org.tolven.component.tolvenweb" point-id="publicDirectory">
     <parameter id="sourceDirectory" value="web/public" />
</extension>
<extension id="scriptsDirectory" plugin-id="org.tolven.component.tolvenweb" point-id="scriptsDirectory">
     <parameter id="sourceDirectory" value="web/scripts" />
</extension>
<extension id="stylesDirectory" plugin-id="org.tolven.component.tolvenweb" point-id="stylesDirectory">
     <parameter id="sourceDirectory" value="web/styles" />
</extension>
<extension id="templatesDirectory" plugin-id="org.tolven.component.tolvenweb" point-id="templatesDirectory">
     <parameter id="sourceDirectory" value="web/templates" />
</extension>
<extension id="wizardDirectory" plugin-id="org.tolven.component.tolvenweb" point-id="wizardDirectory">
     <parameter id="sourceDirectory" value="web/wizard" />
</extension>
 -->
<!-- 
	Add a value to a property associated with a specific class.
	Copy this prototype for each property added to a class in EJB
	The class name is the one being configured. The name and value of the property
	are defined by that class. 
	In many cases, the value is the name of your class, below.
	Add an override parameter...
	   <parameter id="override" value="existingProperty" />
	if this extension is overriding an existing property setting.
<extension id="property" plugin-id="org.tolven.component.tolvenejb" point-id="property">
     <parameter id="class" value="com.myorg.SomeClass" />
     <parameter id="name" value="myProperty1" />
     <parameter id="value" value="myProperty1Value" />
</extension>
 -->
<!-- 
	Uncomment this extension to include classes that will be deployed to the EJB component
	Also, be sure your build file includes the /ejb section
<extension id="ejbclasses" plugin-id="org.tolven.component.tolvenejb" point-id="classes">
     <parameter id="dir" value="ejb/classes" />
</extension>
 -->

</plugin>

=== dubrsl/tolven/org.tolven.assembler.connectormodule/manifest/tolven-plugin.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<plugin id="org.tolven.assembler.library" version="2.0.3" class="org.tolven.assembler.library.LibraryAssembler" vendor="Tolven" xsi:schemaLocation="urn:tolven-org:tpf:1.0 http://tolven.org/xsd/tpf.xsd" xmlns="urn:tolven-org:tpf:1.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
	<requires>
		<import plugin-id="org.tolven.component.library" />
	</requires>
	<runtime>
		<library type="code" path="tpf/classes/" id="classes" />
	</runtime>
	<extension-point extension-multiplicity="none" id="devLib">
		<parameter-def default-value="devLib.jar" id="jar" />
	</extension-point>
	<extension-point id="abstractLib" parent-plugin-id="org.tolven.component.library" parent-point-id="abstractLib" extension-multiplicity="none" />
</plugin>

=== dubrsl/tolven/trunk/org.tolven.api/manifest/tolven-plugin.xml
<?xml version="1.0" encoding="UTF-8"?>
<plugin id="org.tolven.api" version="2.1.0" vendor="Tolven" xmlns="urn:tolven-org:tpf:1.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="urn:tolven-org:tpf:1.0 http://tolven.org/xsd/tpf.xsd">
	<requires>
		<import plugin-id="org.tolven.component.war" />
		<import plugin-id="org.tolven.component.tolvenear" />
		<import plugin-id="org.tolven.component.composite" />
		<import plugin-id="org.tolven.assembler.war" />
		<import plugin-id="org.tolven.jaxrs" />
		<import plugin-id="org.tolven.component.tolvenejb" />
		<import plugin-id="org.tolven.api.schemas" />
	</requires>

	<extension-point id="warModule-declaration" parent-plugin-id="org.tolven.component.war" parent-point-id="warModule-declaration" extension-multiplicity="none">
		<parameter-def id="context-id" default-value="tolvenapi" />
	</extension-point>

	<!-- WAR Services -->
	<extension-point id="WEB-INF-LIB-adaptor" parent-plugin-id="org.tolven.component.war" parent-point-id="WEB-INF-LIB-adaptor" />
	<extension-point id="WEB-INF-CLASSES-adaptor" parent-plugin-id="org.tolven.component.war" parent-point-id="WEB-INF-CLASSES-adaptor" />
	<extension-point id="WEB-ROOT-FILES-adaptor" parent-plugin-id="org.tolven.component.war" parent-point-id="WEB-ROOT-FILES-adaptor" />
	<extension-point id="webDirectory-adaptor" parent-plugin-id="org.tolven.component.war" parent-point-id="webDirectory-adaptor" />
	<!-- WAR Services End -->

	<extension id="warModule" plugin-id="org.tolven.component.tolvenear" point-id="warModule">
		<parameter id="web-uri" value="tolvenAPI.war" />
		<parameter id="context-root" value="/api" />
	</extension>
	<extension id="composite" plugin-id="org.tolven.component.composite" point-id="composite">
		<parameter id="name" value="tolvenRESTfulAPI" />
	</extension>
	<extension id="compositeExtensionPoint.war" plugin-id="org.tolven.component.war" point-id="compositeExtensionPoint">
		<parameter id="name" value="war" />
	</extension>
	<extension-point id="devLib" extension-multiplicity="none">
		<parameter-def id="jar" default-value="devLib.jar" />
	</extension-point>

	<!-- WEB-INF ExtensionPoint -->
	<extension-point id="WEB-INF-LIB" parent-plugin-id="org.tolven.assembler.war" parent-point-id="WEB-INF-LIB">
		<parameter-def id="jar" />
	</extension-point>

	<!-- Classes ExtensionPoint -->
	<extension-point id="classes" parent-plugin-id="org.tolven.assembler.war" parent-point-id="classes">
		<parameter-def id="dir" />
	</extension-point>

	<!-- Filters -->
	<extension id="GeneralSecurityFilter" plugin-id="org.tolven.component.war" point-id="filter">
		<parameter id="filter-name" value="GeneralSecurityFilter" />
		<parameter id="filter-class" value="org.tolven.api.security.GeneralSecurityFilter" />
		<parameter id="filter-sequence" value="200" />
		<parameter id="web-resource-name" value="Secure Pages" />
		<parameter id="target-plugin-id" value="org.tolven.api" />
	</extension>
	<extension id="GeneralSecurityFilter-contribution" plugin-id="org.tolven.component.war" point-id="filter-mapping-contribution">
		<parameter id="filter-name" value="GeneralSecurityFilter" />
		<parameter id="url-pattern" value="/*" />
		<parameter id="target-plugin-id" value="org.tolven.api" />
	</extension>
	<!-- End Filters -->

	<!-- Gauntlet Security -->
	<extension id="org.tolven.restful.VestibuleResources-propertySequence" plugin-id="org.tolven.component.war" point-id="propertySequence">
		<parameter id="class" value="org.tolven.restful.VestibuleResources" />
		<parameter id="name" value="vestibuleJNDINames" />
		<parameter id="defaultSequence" value="java:app/tolvenAPI/org.tolven.api.vestibule.QuestionAnswerVestibule,java:app/tolvenAPI/org.tolven.api.vestibule.SelectAccountVestibule" />
		<parameter id="target-plugin-id" value="org.tolven.api" />
	</extension>
	<extension id="org.tolven.api.vestibule.QuestionAnswerVestibule" plugin-id="org.tolven.component.war" point-id="property">
		<parameter id="class" value="org.tolven.restful.VestibuleResources" />
		<parameter id="name" value="vestibuleJNDINames" />
		<parameter id="value" value="java:app/tolvenAPI/org.tolven.api.vestibule.QuestionAnswerVestibule" />
		<parameter id="target-plugin-id" value="org.tolven.api" />
	</extension>
	<extension id="org.tolven.api.vestibule.SelectAccountVestibule" plugin-id="org.tolven.component.war" point-id="property">
		<parameter id="class" value="org.tolven.restful.VestibuleResources" />
		<parameter id="name" value="vestibuleJNDINames" />
		<parameter id="value" value="java:app/tolvenAPI/org.tolven.api.vestibule.SelectAccountVestibule" />
		<parameter id="target-plugin-id" value="org.tolven.api" />
	</extension>
	<!-- End Gauntlet Security -->

	<!-- Security -->
	<extension id="Secure Area-security-constraint" plugin-id="org.tolven.component.war" point-id="security-constraint">
		<parameter id="web-resource-collection">
			<parameter id="web-resource-name" value="Secure pages" />
			<parameter id="url-pattern" value="/*" />
		</parameter>
		<parameter id="transport-guarantee" value="CONFIDENTIAL" />
		<parameter id="target-plugin-id" value="org.tolven.api" />
	</extension>
	<extension id="security-role" plugin-id="org.tolven.component.war" point-id="security-role">
		<parameter id="role-name" value="*" />
		<parameter id="target-plugin-id" value="org.tolven.api" />
	</extension>
	<extension id="env-entry-webContextId" plugin-id="org.tolven.component.war" point-id="env-entry">
		<parameter id="env-entry-name" value="webContextId" />
		<parameter id="env-entry-type" value="java.lang.String" />
		<parameter id="env-entry-value" value="tolvenapi" />
		<parameter id="target-plugin-id" value="org.tolven.api" />
	</extension>
	<!-- End Security -->

</plugin>

=== dubrsl/tolven/trunk/org.tolven.component.application/manifest/tolven-plugin.xml
<?xml version="1.0" encoding="UTF-8"?>
<plugin xmlns="urn:tolven-org:tpf:1.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="urn:tolven-org:tpf:1.0 http://tolven.org/xsd/tpf.xsd" 
	id="org.tolven.component.application" version="2.0.16" vendor="Tolven"
	class="org.tolven.component.application.Application">

	<requires>
		<import plugin-id="org.tolven.library.application" />
		<import plugin-id="org.tolven.api" />
		<import plugin-id="org.tolven.assembler.admin" />
	</requires>
	<runtime>
		<library id="classes" path="tpf/classes/" type="code" />
	</runtime>
	<extension-point id="devLib" extension-multiplicity="none">
		<parameter-def id="jar" default-value="devLib.jar" />
	</extension-point>
	<extension-point id="applications">
		<parameter-def id="dir"/>
	</extension-point>
	<extension-point id="rules">
		<parameter-def id="dir" />
	</extension-point>
	<extension-point id="trims">
		<parameter-def id="dir" />
	</extension-point>
	<extension-point id="reports">
		<parameter-def id="dir" />
	</extension-point>
	<extension id="apiClasses" plugin-id="org.tolven.api" point-id="classes">
		<parameter id="dir" value="api/classes" />
	</extension>
	<extension id="authRestful" plugin-id="org.tolven.assembler.admin" point-id="authRestful">
		<parameter id="authRestful.url" value="#{pluginProperty['authRestful.url']}" />
	</extension>
	<extension id="appRestful" plugin-id="org.tolven.assembler.admin" point-id="appRestful">
		<parameter id="appRestful.url" value="#{pluginProperty['appRestful.url']}" />
	</extension>
</plugin>

=== dubrsl/tolven/tolvenPlugin/org.tolven.config.glassfishcredentials/tolven-plugin.xml
<?xml version="1.0" encoding="UTF-8"?>
<plugin id="org.tolven.config.glassfishcredentials" version="2.1.0" vendor="Tolven" xmlns="urn:tolven-org:tpf:1.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="urn:tolven-org:tpf:1.0 http://tolven.org/xsd/tpf.xsd">
	<requires>
		<import plugin-id="org.tolven.assembler.admin" />
	</requires>
	<extension id="appserver" plugin-id="org.tolven.assembler.admin" point-id="appserver">
		<parameter id="appserver.groupId" value="#{pluginProperty['appserver.groupId']}" />
		<parameter id="appserverSSL.keyStoreFile" value="#{pluginProperty['appserverSSL.keyStoreFile']}" />
		<parameter id="appserverSSL.keyStoreType" value="#{pluginProperty['appserverSSL.keyStoreType']}" />
		<parameter id="appserverSSL.trustStoreFile" value="#{pluginProperty['appserverSSL.trustStoreFile']}" />
		<parameter id="appserverSSL.trustStoreType" value="#{pluginProperty['appserverSSL.trustStoreType']}" />
		<parameter id="appserverSSL.trusted.groups" value="#{pluginProperty['appserverSSL.trusted.groups']}" />
		<parameter id="appserver.credentialDir" value="#{pluginProperty['appserver.credentialDir']}" />
		<parameter id="appserver.active" value="#{pluginProperty['appserver.active']}" />
	</extension>
</plugin>

=== dubrsl/tolven/org.tolven.analysis.smoking/manifest/tolven-plugin.xml
<?xml version="1.0" encoding="UTF-8"?>
<plugin id="org.tolven.analysis.smoking" version="2.0.6" vendor="Tolven" xmlns="urn:tolven-org:tpf:1.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="urn:tolven-org:tpf:1.0 http://tolven.org/xsd/tpf.xsd">
	<requires>
		<import plugin-id="org.tolven.component.application" />
		<import plugin-id="org.tolven.component.tolvenweb" />
		<import plugin-id="org.tolven.component.tolvenlocale" />
		<import plugin-id="org.tolven.component.war" />
		<import plugin-id="org.tolven.component.faces" />
		<import plugin-id="org.tolven.component.tolvenejb" />
		<import plugin-id="org.tolven.analysis" />
	</requires>
	<extension id="applications" plugin-id="org.tolven.component.application" point-id="applications">
		<parameter id="dir" value="app" />
	</extension>
	<!--<extension id="rules" plugin-id="org.tolven.component.application" point-id="rules">
		<parameter id="dir" value="app/rules" />
	</extension>-->
	<extension id="fiveDirectory" plugin-id="org.tolven.component.tolvenweb" point-id="fiveDirectory">
		<parameter id="sourceDirectory" value="web/five" />
	</extension>
	<extension id="manageDirectory" plugin-id="org.tolven.component.tolvenweb" point-id="manageDirectory">
		<parameter id="sourceDirectory" value="web/manage" />
	</extension>
	<extension id="locale-en-application-locale" plugin-id="org.tolven.component.tolvenlocale" point-id="application-locale">
		<parameter id="application-name" value="echr" />
		<parameter id="properties-file" value="locale_en/echr/AppBundle_en.properties" />
	</extension>
	<extension id="org.tolven.cohort.smk-property" plugin-id="org.tolven.component.tolvenejb" point-id="property">
		<parameter id="class" value="org.tolven.analysis.bean.SnapshotBean" />
		<parameter id="name" value="org.tolven.cohort.smk" />
		<parameter id="value" value="java:global/tolven/tolvenEJB/AnalysisChartBean!org.tolven.analysis.CohortSnapshotLocal" />
	</extension>
	<extension id="org.tolven.cohort.smk-navigation-rule-contribution" plugin-id="org.tolven.component.faces" point-id="navigation-rule-contribution">
		<parameter id="from-view-id" value="/manage/analysis/analysisAdmin.xhtml" />
		<parameter id="navigation-case">
			<parameter id="from-action" value="#{top.navAction}" />
			<parameter id="from-outcome" value="org.tolven.cohort.smk" />
			<parameter id="to-view-id" value="/manage/analysis/smkAnalysisAdmin.xhtml" />
		</parameter>
		<parameter id="target-plugin-id" value="org.tolven.component.tolvenweb" />
	</extension>
	<extension id="org.tolven.cohort.smk.smkprogsnapshot-navigation-rule-contribution" plugin-id="org.tolven.component.faces" point-id="navigation-rule-contribution">
		<parameter id="from-view-id" value="/manage/analysis/analysisAdmin.xhtml" />
		<parameter id="navigation-case">
			<parameter id="from-action" value="#{top.navAction}" />
			<parameter id="from-outcome" value="org.tolven.cohort.smk.smkprogsnapshot" />
			<parameter id="to-view-id" value="/manage/analysis/smksmkprogAnalysisAdmin.xhtml" />
		</parameter>
		<parameter id="target-plugin-id" value="org.tolven.component.tolvenweb" />
	</extension>
</plugin>
