=== dubrsl/tolven/trunk/org.tolven.component.tolvenejb/resources/xsd/menuStructure.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns="urn:tolven-org:menuStructure:1.0" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:app="urn:tolven-org:menuStructure:1.0" xmlns:jaxb="http://java.sun.com/xml/ns/jaxb" xmlns:xjc="http://java.sun.com/xml/ns/jaxb/xjc" xmlns:ns1="urn:tolven-org:menuStructure:1.0" targetNamespace="urn:tolven-org:menuStructure:1.0" elementFormDefault="qualified" attributeFormDefault="unqualified" jaxb:version="2.1" jaxb:extensionBindingPrefixes="xjc">
	<xs:annotation>
		<xs:appinfo>
			<jaxb:globalBindings>
				<xjc:simple/>
				<xjc:serializable /> 
			</jaxb:globalBindings>
		</xs:appinfo>
	</xs:annotation>
	<xs:element name="application" type="Application"/>
	<xs:complexType name="Application">
		<xs:sequence>
			<xs:element name="depends" type="xs:string" minOccurs="0" maxOccurs="unbounded"/>
			<xs:element name="rules" type="xs:string" minOccurs="0" maxOccurs="unbounded"/>
			<xs:element name="property" type="AccountProperty" minOccurs="0" maxOccurs="unbounded"/>
			<xs:element name="notice" type="Notice" minOccurs="0" maxOccurs="unbounded"/>
			<xs:element name="trimMenu" type="Placeholder" minOccurs="0" maxOccurs="unbounded"/>
			<xs:element name="menu" type="Menu" minOccurs="0" maxOccurs="1"/>
			<xs:element name="placeholder" type="Placeholder" minOccurs="0" maxOccurs="unbounded"/>
			<xs:element name="extends" type="Extends" minOccurs="0" maxOccurs="unbounded"/>
		</xs:sequence>
		<xs:attribute name="name" type="xs:string"/>
		<xs:attribute name="title" type="xs:string"/>
		<xs:attribute name="homePage" type="xs:string"/>
		<xs:attribute name="logo" type="xs:string"/>
		<xs:attribute name="css" type="xs:string"/>
		<xs:attribute name="creatable" type="xs:boolean"/>
		<xs:attribute name="createAccountPage" type="xs:string"/>
	</xs:complexType>
	<xs:complexType name="Notice">
		<xs:sequence>
			<xs:element name="subject" type="xs:string" minOccurs="0"/>
			<xs:element name="body" type="InvitationBody" minOccurs="0" maxOccurs="unbounded"/>
		</xs:sequence>
		<xs:attribute name="name" type="xs:string"/>
		<xs:attribute name="handler" type="xs:string" use="optional"/>
	</xs:complexType>
	<xs:complexType name="InvitationBody">
		<xs:attribute name="file" type="xs:string"/>
		<xs:attribute name="mimeType" type="xs:string"/>
		<xs:attribute name="locale" type="xs:string" use="optional"/>
	</xs:complexType>
	<xs:complexType name="Extends">
		<xs:sequence>
			<xs:choice>
				<xs:element name="band" type="Band" />
				<xs:element name="calendar" type="Calendar"/>
				<xs:element name="instance" type="Instance" />
				<xs:element name="entry" type="Entry" />
				<xs:element name="list" type="List" />
				<xs:element name="menu" type="Menu" />
				<xs:element name="portal" type="Portal"/>
				<xs:element name="portlet" type="Portlet"/>
				<xs:element name="timeline" type="Timeline"/>
				<xs:element name="trimList" type="TrimList" />
				<xs:element name="placeholder" type="Placeholder"/>
				<xs:element name="field" type="PlaceholderField"/>
				<xs:element name="column" type="Column"/>
			</xs:choice>
		</xs:sequence>
		<xs:attribute name="path" type="xs:string"/>
		<xs:attribute name="optional" type="xs:boolean" use="optional" default="false"/>
		<xs:attribute name="before" type="xs:string" use="optional"/>
		<xs:attribute name="after" type="xs:string" use="optional"/>
	</xs:complexType>
	<xs:complexType name="AccountProperty">
	    <xs:simpleContent>
	      <xs:extension base="xs:string">
			<xs:attribute name="name" type="xs:string" use="required"/>
			<xs:attribute name="file" type="xs:string"/>
			<xs:attribute name="accountType" type="xs:string" use="optional"/>
			<xs:attribute name="account" type="xs:long" use="optional"/>
	      </xs:extension>
	    </xs:simpleContent>
	</xs:complexType>
	<xs:complexType name="MenuBase" abstract="true">
		<xs:sequence>
			<xs:element name="menuEventHandler" type="MenuEventHandler" minOccurs="0" maxOccurs="1"/>
		</xs:sequence>
		<xs:attribute name="name" type="xs:string" use="required"/>
		<xs:attribute name="path" type="xs:string"/>
		<xs:attribute name="title" type="xs:string"/>
		<xs:attribute name="page" type="xs:string"/>
		<xs:attribute name="visible" type="xs:string"/>
		<xs:attribute name="sequence" type="xs:long" use="optional"/>
	</xs:complexType>
	<xs:complexType name="Placeholder">
		<xs:complexContent>
			<xs:extension base="MenuBase">
				<xs:sequence>
					<xs:element name="field" type="PlaceholderField" minOccurs="0" maxOccurs="unbounded"/>
					<xs:choice minOccurs="0" maxOccurs="unbounded">
						<xs:element name="menu" type="Menu" />
						<xs:element name="portal" type="Portal"/>
						<xs:element name="timeline" type="Timeline"/>
						<xs:element name="calendar" type="Calendar"/>
						<xs:element name="list" type="List" />
						<xs:element name="trimList" type="TrimList" />
						<xs:element name="instance" type="Instance" />
					</xs:choice>
					<xs:element name="placeholder" type="Placeholder" minOccurs="0" maxOccurs="unbounded"/>
				</xs:sequence>
				<xs:attribute name="heading" type="xs:string"/>
				<xs:attribute name="initialSort" type="xs:string" use="optional"/>
				<xs:attribute name="eventInstance" type="xs:string">
				</xs:attribute>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	<xs:complexType name="Menu">
		<xs:complexContent>
			<xs:extension base="MenuBase">
				<xs:choice minOccurs="0" maxOccurs="unbounded">
					<xs:element name="menu" type="Menu" />
					<xs:element name="portal" type="Portal"/>
					<xs:element name="timeline" type="Timeline"/>
					<xs:element name="calendar" type="Calendar"/>
					<xs:element name="list" type="List" />
					<xs:element name="trimList" type="TrimList" />
					<xs:element name="instance" type="Instance" />
				</xs:choice>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	<xs:complexType name="Portal">
		<xs:complexContent>
			<xs:extension base="MenuBase">
				<xs:sequence>
					<xs:choice minOccurs="0" maxOccurs="unbounded">
						<xs:element name="portletColumn" type="PortletColumn" />
					</xs:choice>
				</xs:sequence>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	<xs:complexType name="Portlet">
		<xs:complexContent>
			<xs:extension base="MenuBase">
				<xs:sequence>
					<xs:element name="column" type="Column" minOccurs="0" maxOccurs="unbounded"/>
					<xs:element name="action" type="Action" minOccurs="0" maxOccurs="unbounded"/>
				</xs:sequence>
				<xs:attribute name="drilldown" type="xs:string"/>
				<xs:attribute name="filter" type="xs:string" use="optional"/>
				<xs:attribute name="query" type="xs:string" use="optional"/>
				<xs:attribute name="initialSort" type="xs:string" use="optional"/>
				<xs:attribute name="portalColumn" type="xs:long" use="optional"/>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	<xs:complexType name="PortletColumn">
		<xs:sequence>
			<xs:element name="portlet" type="Portlet" minOccurs="0" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="Instance">
		<xs:complexContent>
			<xs:extension base="MenuBase">
				<xs:attribute name="heading" type="xs:string"/>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	<xs:complexType name="List">
		<xs:complexContent>
			<xs:extension base="MenuBase">
				<xs:sequence>
					<xs:element name="column" type="Column" minOccurs="0" maxOccurs="unbounded"/>
					<xs:element name="action" type="Action" minOccurs="0" maxOccurs="unbounded"/>
				</xs:sequence>
				<xs:attribute name="drilldown" type="xs:string"/>
				<xs:attribute name="filter" type="xs:string" use="optional"/>
				<xs:attribute name="query" type="xs:string" use="optional"/>
				<xs:attribute name="initialSort" type="xs:string" use="optional"/>
				<xs:attribute name="uniqueKey" type="xs:string" use="optional"/>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	<xs:complexType name="Action">
		<xs:complexContent>
			<xs:extension base="MenuBase">
				<xs:sequence>
					<xs:element name="column" type="Column" minOccurs="0" maxOccurs="unbounded"/>
				</xs:sequence>
				<xs:attribute name="query" type="xs:string" use="optional"/>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	<xs:complexType name="MenuEventHandler">
		<xs:sequence>
			<xs:element name="data" minOccurs="0" maxOccurs="unbounded">
				<xs:complexType>
					<xs:attribute name="name" type="xs:string"/>
					<xs:attribute name="value" type="xs:string"/>
				</xs:complexType>
			</xs:element>
		</xs:sequence>
		<xs:attribute name="factory" type="xs:string"/>
	</xs:complexType>
	<xs:complexType name="TrimList">
		<xs:complexContent>
			<xs:extension base="MenuBase">
				<xs:sequence>
					<xs:element name="column" type="Column" minOccurs="0" maxOccurs="unbounded"/>
				</xs:sequence>
				<xs:attribute name="placeholder" type="xs:string"/>
				<xs:attribute name="initialSort" type="xs:string" use="optional"/>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	<xs:complexType name="PlaceholderField">
		<xs:sequence>
			<xs:element name="from" type="xs:string" minOccurs="0" maxOccurs="unbounded"/>
		</xs:sequence>
		<xs:attribute name="name" type="xs:string"/>
		<xs:attribute name="internal" type="xs:string"/>
		<xs:attribute name="type" type="ColumnType"/>
	</xs:complexType>
	<xs:complexType name="Column">
		<xs:sequence>
			<xs:element name="from" type="xs:string" minOccurs="0" maxOccurs="unbounded"/>
			<xs:element name="output" minOccurs="0" maxOccurs="unbounded">
				<xs:complexType>
					<xs:sequence>
						<xs:any processContents="skip"/>
					</xs:sequence>
					<xs:attribute name="type" type="xs:string" default="_default"/>
				</xs:complexType>
			</xs:element>
		</xs:sequence>
		<xs:attribute name="name" type="xs:string"/>
		<xs:attribute name="title" type="xs:string"/>
		<xs:attribute name="internal" type="xs:string"/>
		<xs:attribute name="type" type="ColumnType"/>
		<xs:attribute name="format" type="xs:string" use="optional"/>
		<xs:attribute name="instantiate" type="xs:boolean" use="optional" default="false"/>
		<xs:attribute name="reference" type="xs:boolean" use="optional" default="false"/>
		<xs:attribute name="supress" type="xs:string" use="optional"/>
		<xs:attribute name="width" type="xs:float"/>
		<xs:attribute name="align" type="Alignment" default="left"/>
		<xs:attribute name="visible" type="xs:string"/>
	</xs:complexType>
	<xs:simpleType name="ColumnType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="string"/>
			<xs:enumeration value="date"/>
			<xs:enumeration value="long"/>
			<xs:enumeration value="double"/>
			<xs:enumeration value="placeholder"/>
			<xs:enumeration value="AD"/>
			<xs:enumeration value="CD"/>
			<xs:enumeration value="ED"/>
			<xs:enumeration value="INT"/>
			<xs:enumeration value="PQ"/>
			<xs:enumeration value="REAL"/>
			<xs:enumeration value="TEL"/>
			<xs:enumeration value="TS"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="Alignment">
		<xs:restriction base="xs:string">
			<xs:enumeration value="left"/>
			<xs:enumeration value="center"/>
			<xs:enumeration value="right"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:complexType name="Timeline">
		<xs:complexContent>
			<xs:extension base="MenuBase">
				<xs:sequence>
					<xs:element name="band" type="Band" minOccurs="0" maxOccurs="unbounded"/>
				</xs:sequence>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	<xs:complexType name="Band">
		<xs:complexContent>
			<xs:extension base="MenuBase">
				<xs:sequence>
					<xs:element name="column" type="Column" minOccurs="0" maxOccurs="unbounded"/>
					<xs:element name="action" type="Action" minOccurs="0" maxOccurs="unbounded"/>
				</xs:sequence>
				<xs:attribute name="drilldown" type="xs:string"/>
				<xs:attribute name="interval" type="BandInterval" use="required"/>
				<xs:attribute name="style" type="xs:string"/>
				<xs:attribute name="query" type="xs:string" use="optional"/>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	<xs:simpleType name="BandInterval">
		<xs:restriction base="xs:token">
			<xs:enumeration value="year"/>
			<xs:enumeration value="month"/>
			<xs:enumeration value="week"/>
			<xs:enumeration value="day"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:complexType name="Calendar">
		<xs:complexContent>
			<xs:extension base="MenuBase">
				<xs:sequence>
					<xs:element name="entry" type="Entry" minOccurs="0" maxOccurs="unbounded"/>
				</xs:sequence>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	<xs:complexType name="Entry">
		<xs:complexContent>
			<xs:extension base="MenuBase">
				<xs:sequence>
					<xs:element name="column" type="Column" minOccurs="0" maxOccurs="unbounded"/>
					<xs:element name="action" type="Action" minOccurs="0" maxOccurs="unbounded"/>
				</xs:sequence>
				<xs:attribute name="drilldown" type="xs:string"/>
				<xs:attribute name="style" type="xs:string"/>
				<xs:attribute name="query" type="xs:string" use="optional"/>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
</xs:schema>

=== dubrsl/tolven/trunk/org.tolven.onc.applications/app/onc-echr-patient-procedure.application.xml
<application xmlns="urn:tolven-org:menuStructure:1.0"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="urn:tolven-org:menuStructure:1.0 http://tolven.org/xsd/menuStructure.xsd">

	<!-- Patient Procedures (px) -->
	<!-- Customized procedure placeholder: 1. Added field for code to use in PLD. -->
	<extends path="echr:patient">
		<placeholder name="px" sequence="15" title="Procedure" eventInstance="echr:patient:wip" heading="/five/treatmentLink.xhtml" page="/wizard/wizard.xhtml">
			<field internal="string01" name="title">
				<from>#{act.code.CE.displayName}</from>
				<from>#{trim.description}</from>
			</field>
			<field name="code" internal="string06">
				<from>#{act.code.CE.translations[0].code}</from>
				<from>#{act.code.CE.code}</from>
			</field>
			<field internal="date01" name="effectiveTimeLow">
				<from>#{act.effectiveTime.TS.date}</from>
				<from>#{act.effectiveTime.IVLTS.low.date}</from>
			</field>
			<field internal="date02" name="effectiveTimeHigh">
				<from>#{act.effectiveTime.IVLTS.high.date}</from>
			</field>
			<field internal="parent01" name="patient">
				<from>#{patient}</from>
			</field>
			<field name="status" internal="string02">
				<from>#{trim.act.statusCode}</from>
			</field>
			<field internal="parent02" name="author">
				<from>#{internalId( account, trim.act.participation['author'].role.id)}</from>
			</field>
			<field internal="string05" name="enteredBy">
				<from>#{internalId( account, trim.act.participation['dataEnterer'].role.id)}</from>
			</field>
		</placeholder>
	</extends>
	<extends path="echr:patient:summary">
		<list name="procsum" visible="never">
			<column name="FromDate" internal="date01" format="MM/dd/yyyy">
				<from>#{procedure.effectiveTimeLow}</from>
				<from>#{px.effectiveTimeLow}</from>
			</column>
			<column name="title" internal="string01">
				<from>#{procedure.title}</from>
				<from>#{px.title}</from>
			</column>
			<column name="status" internal="string02">
				<from>#{px.status}</from>
			</column>
		</list>
	</extends>
	<extends path="echr:patient:summary:portal">
		<portlet name="procsum" portalColumn="3" sequence="3" title="Procedures" page="/five/summaryPortletList.xhtml" query="echr:patient:summary:procsum" visible="true" drilldown=":procedures">
			<action title="New" name="menu1" query="global:pxDocMenu" visible="true" page="/five/list.xhtml">
				<column width="40.0" instantiate="true" internal="string01" name="Procedure" />
			</action>
			<action title="New" name="menu" query="global:pxDocMenu" visible="true" page="/five/list.xhtml">
				<column width="40.0" instantiate="true" internal="string01" name="Procedure" />
			</action>
		</portlet>
	</extends>

	<extends path="echr:patient:summary:calendar">
		<entry name="procedure" sequence="5" title="Procedure" query="echr:patient:summary:procsum" visible="true" drilldown=":procedures" />
	</extends>
	<!-- Customized procedures menu: 1. Added additional column for code to use in PLD. -->
	<extends path="echr:patient">
		<menu name="procedures" sequence="19" title="Procedures" page="/five/bar2.xhtml" visible="true">
			<list name="pxList" title="Current" drilldown=":px" visible="true" page="/five/list.xhtml">
				<column width="10.0" format="MMM-dd-yyyy" internal="date01" name="Date">
					<from>#{px.effectiveTimeLow}</from>
				</column>
				<column width="40.0" reference="true" internal="string01" name="Procedure">
					<from>#{px.title}</from>
				</column>
				<column name="Code" internal="string06" reference="true" width="15.0" visible="false">
					<from>#{px.code}</from>
				</column>
				<column width="15.0" internal="string02" name="Status">
					<from>#{px.status}</from>
				</column>
				<column width="15.0" internal="string03" name="Performer">
					<from>#{px.author.lastName}</from>
					<from>#{px.enteredBy}</from>
				</column>
				<action title="New" name="menu" query="global:pxDocMenu" visible="true" page="/five/list.xhtml">
					<column width="40.0" instantiate="true" internal="string01" name="Procedure" />
				</action>
			</list>
			<list name="nullified" title="Nullified" drilldown=":px" visible="true" page="/five/list.xhtml">
				<column width="10.0" format="MMM-dd-yyyy" internal="date01" name="Date">
					<from>#{px.effectiveTimeLow}</from>
				</column>
				<column width="40.0" reference="true" internal="string01" name="Procedure">
					<from>#{px.title}</from>
				</column>
				<column name="Code" internal="string06" reference="true" width="15.0" visible="false">
					<from>#{px.code}</from>
				</column>
				<column width="15.0" internal="string02" name="Status">
					<from>#{px.status}</from>
				</column>
				<column width="15.0" internal="string03" name="Performer">
					<from>#{px.author.lastName}</from>
					<from>#{px.enteredBy}</from>
				</column>				
			</list>
		</menu>
	</extends>
	</application>

=== dubrsl/tolven/trunk/org.tolven.onc.applications/app/onc-echr-patient-immunization.application.xml
<application xmlns="urn:tolven-org:menuStructure:1.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="urn:tolven-org:menuStructure:1.0 http://tolven.org/xsd/menuStructure.xsd">

	<!-- Patient immunizations -->
	<extends path="echr:patient">
		<placeholder name="immunization" eventInstance="echr:patient:wip" heading="/five/medicationLink.xhtml" page="/wizard/wizard.xhtml" title="Immunization">
			            <field internal="string01" name="title">
                <from>#{act.title.ST.value}</from>
                <from>#{trim.description}</from>
            </field>
            <field internal="date01" name="effectiveTimeLow">
                <from>#{act.effectiveTime.TS.date}</from>
                <from>#{act.effectiveTime.IVLTS.low.date}</from>
            </field>
            <field internal="date02" name="effectiveTimeHigh">
                <from>#{act.effectiveTime.IVLTS.high.date}</from>
            </field>
            <field internal="parent01" name="patient">
                <from>#{patient}</from>
            </field>
            <field internal="parent02" name="author">
                <from>#{internalId( account, act.participation['author'].role.id)}</from>
            </field>
            <field internal="parent03" name="encounter">
                <from>#{internalId( account, act.relationship['encounter'].act.id)}</from>
            </field>
			<field name="refillNumber" internal="long01">
				<from>#{trim.act.repeatNumber.INT.value}</from>
			</field>
			<field name="dosageQuantity" internal="pqValue01">
				<from>#{trim.act.substanceAdministration.doseQuantity.PQ.value}</from>
			</field>
			<field name="consumableMaterial" internal="pqValue02"> 
				<from>#{trim.act.participation['consumable'].role.player.quantity.PQ.value}</from>
			</field>
			<field name="dosagequantityUnit" internal="pqUnits01">
				<from>#{trim.act.substanceAdministration.doseQuantity.PQ.unit}</from>
			</field>
			<field name="consumableMaterialUnit" internal="pqUnits02"> 
				<from>#{trim.act.participation['consumable'].role.player.quantity.PQ.unit}</from>
			</field>                
			<field name="lotNumber" internal="string02"> 
				<from>#{trim.act.relationship['LOTnumber'].act.observation.value.ST.value}</from>
			</field>
            <field internal="string05" name="enteredBy">
                <from>#{internalId( account, act.participation['dataEnterer'].role.id)}</from>
            </field>
            <field name="code" internal="string06">
				<from>#{act.participation['consumable'].role.player.code.CE.code}</from>
	        </field>
	        <field name="manufacturerName" internal="string03"> 
				<from>#{trim.act.relationship['manufacturer'].act.observation.values[0].ST.value}</from>
			</field>
			<field name="receiver" internal="string07">
				<from>#{immunization.receiverBy.name}</from>
				<from>#{immunization.receiverFormat}</from>
			</field>
			<field name="receiverBy" internal="parent04">
				<from>#{internalId( account, act.participation['receiver'].role.id)}</from>
			</field>
			<field name="receiverFormat" internal="_extended">
				<from>#{act.participation['receiver'].role.player.name.EN['L'].formatted}</from>
			</field>
			<field name="receiverExtension" internal="_extended">
				<from>#{act.participation['receiver'].role.id.IIS[0].extension}</from>
			</field>
		</placeholder>
	</extends>
	<extends path="echr:patient">
		<menu visible="true" sequence="5" page="/five/bar2.xhtml" title="Immun/Vaccin" name="immu">
			<list drilldown=":immunization" visible="true" page="/five/list.xhtml" title="Current" name="current">
				<column width="15.0" format="MMM-dd-yyyy hh:mm" internal="date01" name="Date">
					<from>#{immunization.effectiveTimeLow}</from>
				</column>
				<column width="40.0" reference="true" internal="string01" name="Immunization">
					<from>#{immunization.title}</from>
				</column>
				<column width="15.0" internal="string03" name="Status" />
				<column width="25.0" internal="string02" name="Source">
					<from>#{immunization.author.lastName}</from>
					<from>#{immunization.enteredBy}</from>
				</column>
				<column name="Code" internal="string06" visible="never">
					<from>#{immunization.code}</from>
				</column>
				<action name="menu" title="New" page="/five/list.xhtml" visible="true" query="global:immunizationMenu">
					<column name="Immunization" internal="string01" instantiate="true" width="40.0" />
				</action>
			</list>
		</menu>
	</extends>
	<!-- Added Portlet for immunization -->
	<extends path="echr:patient:summary">
		<list name="immusum" visible="never">
			<column name="effectiveTime" internal="date01" format="MM/dd/yyyy">
				<from>#{immunization.effectiveTimeLow}</from>
			</column>
			<column name="title" internal="string01">
				<from>#{immunization.title}</from>
			</column>
		</list>
	</extends>
	<extends path="echr:patient:summary:portal">
		<portlet name="immusum" portalColumn="1" sequence="1" title="Immunizations" page="/five/summaryPortletList.xhtml" query="echr:patient:summary:immusum" visible="true" drilldown=":immu">
			<action name="menu" title="New" page="/five/list.xhtml" visible="true" query="global:immunizationMenu">
				<column name="Immunization" internal="string01" instantiate="true" width="40.0" />
			</action>
		</portlet>
	</extends>
</application>
