=== dubrsl/tolven/trunk/org.tolven.component.tolvenejb/resources/xsd/menuStructure.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns="urn:tolven-org:menuStructure:1.0" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:app="urn:tolven-org:menuStructure:1.0" xmlns:jaxb="http://java.sun.com/xml/ns/jaxb" xmlns:xjc="http://java.sun.com/xml/ns/jaxb/xjc" xmlns:ns1="urn:tolven-org:menuStructure:1.0" targetNamespace="urn:tolven-org:menuStructure:1.0" elementFormDefault="qualified" attributeFormDefault="unqualified" jaxb:version="2.1" jaxb:extensionBindingPrefixes="xjc">
	<xs:annotation>
		<xs:appinfo>
			<jaxb:globalBindings>
				<xjc:simple/>
				<xjc:serializable /> 
			</jaxb:globalBindings>
		</xs:appinfo>
	</xs:annotation>
	<xs:element name="application" type="Application"/>
	<xs:complexType name="Application">
		<xs:sequence>
			<xs:element name="depends" type="xs:string" minOccurs="0" maxOccurs="unbounded"/>
			<xs:element name="rules" type="xs:string" minOccurs="0" maxOccurs="unbounded"/>
			<xs:element name="property" type="AccountProperty" minOccurs="0" maxOccurs="unbounded"/>
			<xs:element name="notice" type="Notice" minOccurs="0" maxOccurs="unbounded"/>
			<xs:element name="trimMenu" type="Placeholder" minOccurs="0" maxOccurs="unbounded"/>
			<xs:element name="menu" type="Menu" minOccurs="0" maxOccurs="1"/>
			<xs:element name="placeholder" type="Placeholder" minOccurs="0" maxOccurs="unbounded"/>
			<xs:element name="extends" type="Extends" minOccurs="0" maxOccurs="unbounded"/>
		</xs:sequence>
		<xs:attribute name="name" type="xs:string"/>
		<xs:attribute name="title" type="xs:string"/>
		<xs:attribute name="homePage" type="xs:string"/>
		<xs:attribute name="logo" type="xs:string"/>
		<xs:attribute name="css" type="xs:string"/>
		<xs:attribute name="creatable" type="xs:boolean"/>
		<xs:attribute name="createAccountPage" type="xs:string"/>
	</xs:complexType>
	<xs:complexType name="Notice">
		<xs:sequence>
			<xs:element name="subject" type="xs:string" minOccurs="0"/>
			<xs:element name="body" type="InvitationBody" minOccurs="0" maxOccurs="unbounded"/>
		</xs:sequence>
		<xs:attribute name="name" type="xs:string"/>
		<xs:attribute name="handler" type="xs:string" use="optional"/>
	</xs:complexType>
	<xs:complexType name="InvitationBody">
		<xs:attribute name="file" type="xs:string"/>
		<xs:attribute name="mimeType" type="xs:string"/>
		<xs:attribute name="locale" type="xs:string" use="optional"/>
	</xs:complexType>
	<xs:complexType name="Extends">
		<xs:sequence>
			<xs:choice>
				<xs:element name="band" type="Band" />
				<xs:element name="calendar" type="Calendar"/>
				<xs:element name="instance" type="Instance" />
				<xs:element name="entry" type="Entry" />
				<xs:element name="list" type="List" />
				<xs:element name="menu" type="Menu" />
				<xs:element name="portal" type="Portal"/>
				<xs:element name="portlet" type="Portlet"/>
				<xs:element name="timeline" type="Timeline"/>
				<xs:element name="trimList" type="TrimList" />
				<xs:element name="placeholder" type="Placeholder"/>
				<xs:element name="field" type="PlaceholderField"/>
				<xs:element name="column" type="Column"/>
			</xs:choice>
		</xs:sequence>
		<xs:attribute name="path" type="xs:string"/>
		<xs:attribute name="optional" type="xs:boolean" use="optional" default="false"/>
		<xs:attribute name="before" type="xs:string" use="optional"/>
		<xs:attribute name="after" type="xs:string" use="optional"/>
	</xs:complexType>
	<xs:complexType name="AccountProperty">
	    <xs:simpleContent>
	      <xs:extension base="xs:string">
			<xs:attribute name="name" type="xs:string" use="required"/>
			<xs:attribute name="file" type="xs:string"/>
			<xs:attribute name="accountType" type="xs:string" use="optional"/>
			<xs:attribute name="account" type="xs:long" use="optional"/>
	      </xs:extension>
	    </xs:simpleContent>
	</xs:complexType>
	<xs:complexType name="MenuBase" abstract="true">
		<xs:sequence>
			<xs:element name="menuEventHandler" type="MenuEventHandler" minOccurs="0" maxOccurs="1"/>
		</xs:sequence>
		<xs:attribute name="name" type="xs:string" use="required"/>
		<xs:attribute name="path" type="xs:string"/>
		<xs:attribute name="title" type="xs:string"/>
		<xs:attribute name="page" type="xs:string"/>
		<xs:attribute name="visible" type="xs:string"/>
		<xs:attribute name="sequence" type="xs:long" use="optional"/>
	</xs:complexType>
	<xs:complexType name="Placeholder">
		<xs:complexContent>
			<xs:extension base="MenuBase">
				<xs:sequence>
					<xs:element name="field" type="PlaceholderField" minOccurs="0" maxOccurs="unbounded"/>
					<xs:choice minOccurs="0" maxOccurs="unbounded">
						<xs:element name="menu" type="Menu" />
						<xs:element name="portal" type="Portal"/>
						<xs:element name="timeline" type="Timeline"/>
						<xs:element name="calendar" type="Calendar"/>
						<xs:element name="list" type="List" />
						<xs:element name="trimList" type="TrimList" />
						<xs:element name="instance" type="Instance" />
					</xs:choice>
					<xs:element name="placeholder" type="Placeholder" minOccurs="0" maxOccurs="unbounded"/>
				</xs:sequence>
				<xs:attribute name="heading" type="xs:string"/>
				<xs:attribute name="initialSort" type="xs:string" use="optional"/>
				<xs:attribute name="eventInstance" type="xs:string">
				</xs:attribute>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	<xs:complexType name="Menu">
		<xs:complexContent>
			<xs:extension base="MenuBase">
				<xs:choice minOccurs="0" maxOccurs="unbounded">
					<xs:element name="menu" type="Menu" />
					<xs:element name="portal" type="Portal"/>
					<xs:element name="timeline" type="Timeline"/>
					<xs:element name="calendar" type="Calendar"/>
					<xs:element name="list" type="List" />
					<xs:element name="trimList" type="TrimList" />
					<xs:element name="instance" type="Instance" />
				</xs:choice>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	<xs:complexType name="Portal">
		<xs:complexContent>
			<xs:extension base="MenuBase">
				<xs:sequence>
					<xs:choice minOccurs="0" maxOccurs="unbounded">
						<xs:element name="portletColumn" type="PortletColumn" />
					</xs:choice>
				</xs:sequence>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	<xs:complexType name="Portlet">
		<xs:complexContent>
			<xs:extension base="MenuBase">
				<xs:sequence>
					<xs:element name="column" type="Column" minOccurs="0" maxOccurs="unbounded"/>
					<xs:element name="action" type="Action" minOccurs="0" maxOccurs="unbounded"/>
				</xs:sequence>
				<xs:attribute name="drilldown" type="xs:string"/>
				<xs:attribute name="filter" type="xs:string" use="optional"/>
				<xs:attribute name="query" type="xs:string" use="optional"/>
				<xs:attribute name="initialSort" type="xs:string" use="optional"/>
				<xs:attribute name="portalColumn" type="xs:long" use="optional"/>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	<xs:complexType name="PortletColumn">
		<xs:sequence>
			<xs:element name="portlet" type="Portlet" minOccurs="0" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="Instance">
		<xs:complexContent>
			<xs:extension base="MenuBase">
				<xs:attribute name="heading" type="xs:string"/>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	<xs:complexType name="List">
		<xs:complexContent>
			<xs:extension base="MenuBase">
				<xs:sequence>
					<xs:element name="column" type="Column" minOccurs="0" maxOccurs="unbounded"/>
					<xs:element name="action" type="Action" minOccurs="0" maxOccurs="unbounded"/>
				</xs:sequence>
				<xs:attribute name="drilldown" type="xs:string"/>
				<xs:attribute name="filter" type="xs:string" use="optional"/>
				<xs:attribute name="query" type="xs:string" use="optional"/>
				<xs:attribute name="initialSort" type="xs:string" use="optional"/>
				<xs:attribute name="uniqueKey" type="xs:string" use="optional"/>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	<xs:complexType name="Action">
		<xs:complexContent>
			<xs:extension base="MenuBase">
				<xs:sequence>
					<xs:element name="column" type="Column" minOccurs="0" maxOccurs="unbounded"/>
				</xs:sequence>
				<xs:attribute name="query" type="xs:string" use="optional"/>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	<xs:complexType name="MenuEventHandler">
		<xs:sequence>
			<xs:element name="data" minOccurs="0" maxOccurs="unbounded">
				<xs:complexType>
					<xs:attribute name="name" type="xs:string"/>
					<xs:attribute name="value" type="xs:string"/>
				</xs:complexType>
			</xs:element>
		</xs:sequence>
		<xs:attribute name="factory" type="xs:string"/>
	</xs:complexType>
	<xs:complexType name="TrimList">
		<xs:complexContent>
			<xs:extension base="MenuBase">
				<xs:sequence>
					<xs:element name="column" type="Column" minOccurs="0" maxOccurs="unbounded"/>
				</xs:sequence>
				<xs:attribute name="placeholder" type="xs:string"/>
				<xs:attribute name="initialSort" type="xs:string" use="optional"/>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	<xs:complexType name="PlaceholderField">
		<xs:sequence>
			<xs:element name="from" type="xs:string" minOccurs="0" maxOccurs="unbounded"/>
		</xs:sequence>
		<xs:attribute name="name" type="xs:string"/>
		<xs:attribute name="internal" type="xs:string"/>
		<xs:attribute name="type" type="ColumnType"/>
	</xs:complexType>
	<xs:complexType name="Column">
		<xs:sequence>
			<xs:element name="from" type="xs:string" minOccurs="0" maxOccurs="unbounded"/>
			<xs:element name="output" minOccurs="0" maxOccurs="unbounded">
				<xs:complexType>
					<xs:sequence>
						<xs:any processContents="skip"/>
					</xs:sequence>
					<xs:attribute name="type" type="xs:string" default="_default"/>
				</xs:complexType>
			</xs:element>
		</xs:sequence>
		<xs:attribute name="name" type="xs:string"/>
		<xs:attribute name="title" type="xs:string"/>
		<xs:attribute name="internal" type="xs:string"/>
		<xs:attribute name="type" type="ColumnType"/>
		<xs:attribute name="format" type="xs:string" use="optional"/>
		<xs:attribute name="instantiate" type="xs:boolean" use="optional" default="false"/>
		<xs:attribute name="reference" type="xs:boolean" use="optional" default="false"/>
		<xs:attribute name="supress" type="xs:string" use="optional"/>
		<xs:attribute name="width" type="xs:float"/>
		<xs:attribute name="align" type="Alignment" default="left"/>
		<xs:attribute name="visible" type="xs:string"/>
	</xs:complexType>
	<xs:simpleType name="ColumnType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="string"/>
			<xs:enumeration value="date"/>
			<xs:enumeration value="long"/>
			<xs:enumeration value="double"/>
			<xs:enumeration value="placeholder"/>
			<xs:enumeration value="AD"/>
			<xs:enumeration value="CD"/>
			<xs:enumeration value="ED"/>
			<xs:enumeration value="INT"/>
			<xs:enumeration value="PQ"/>
			<xs:enumeration value="REAL"/>
			<xs:enumeration value="TEL"/>
			<xs:enumeration value="TS"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="Alignment">
		<xs:restriction base="xs:string">
			<xs:enumeration value="left"/>
			<xs:enumeration value="center"/>
			<xs:enumeration value="right"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:complexType name="Timeline">
		<xs:complexContent>
			<xs:extension base="MenuBase">
				<xs:sequence>
					<xs:element name="band" type="Band" minOccurs="0" maxOccurs="unbounded"/>
				</xs:sequence>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	<xs:complexType name="Band">
		<xs:complexContent>
			<xs:extension base="MenuBase">
				<xs:sequence>
					<xs:element name="column" type="Column" minOccurs="0" maxOccurs="unbounded"/>
					<xs:element name="action" type="Action" minOccurs="0" maxOccurs="unbounded"/>
				</xs:sequence>
				<xs:attribute name="drilldown" type="xs:string"/>
				<xs:attribute name="interval" type="BandInterval" use="required"/>
				<xs:attribute name="style" type="xs:string"/>
				<xs:attribute name="query" type="xs:string" use="optional"/>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	<xs:simpleType name="BandInterval">
		<xs:restriction base="xs:token">
			<xs:enumeration value="year"/>
			<xs:enumeration value="month"/>
			<xs:enumeration value="week"/>
			<xs:enumeration value="day"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:complexType name="Calendar">
		<xs:complexContent>
			<xs:extension base="MenuBase">
				<xs:sequence>
					<xs:element name="entry" type="Entry" minOccurs="0" maxOccurs="unbounded"/>
				</xs:sequence>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	<xs:complexType name="Entry">
		<xs:complexContent>
			<xs:extension base="MenuBase">
				<xs:sequence>
					<xs:element name="column" type="Column" minOccurs="0" maxOccurs="unbounded"/>
					<xs:element name="action" type="Action" minOccurs="0" maxOccurs="unbounded"/>
				</xs:sequence>
				<xs:attribute name="drilldown" type="xs:string"/>
				<xs:attribute name="style" type="xs:string"/>
				<xs:attribute name="query" type="xs:string" use="optional"/>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
</xs:schema>

=== dubrsl/tolven/trunk/org.tolven.onc.applications/app/onc-echr-patient-problem.application.xml
<application xmlns="urn:tolven-org:menuStructure:1.0"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="urn:tolven-org:menuStructure:1.0 http://tolven.org/xsd/menuStructure.xsd">
	<!-- Patient problems -->
	<!-- Customized problem placeholder: 1. Added field for status 2. Added 
		field for code to use in PLD. 3. Modified author and enteredBy field -->
	<extends path="echr:patient">
		<placeholder name="problem" title="Problem" eventInstance="echr:patient:wip" page="/wizard/wizard.xhtml" heading="/five/problemLink.xhtml">
			<field name="title" internal="string01">
				<from>#{act.observation.value.CE.displayName}</from>
				<from>#{act.title.ST.value}</from>
				<from>#{trim.description}</from>
			</field>
			<field name="code" internal="string06">
				<from>#{act.observation.value.CE.code}</from>
				<from>#{act.code.CD.code}</from>
			</field>
			<field name="effectiveTimeLow" internal="date01">
				<from>#{act.effectiveTime.TS.date}</from>
				<from>#{act.effectiveTime.IVLTS.low.date}</from>
			</field>
			<field name="effectiveTimeHigh" internal="date02">
				<from>#{act.effectiveTime.IVLTS.high.date}</from>
			</field>
			<field name="availabilityTime" internal="updatetime"/>
			<field name="patient" internal="parent01">
				<from>#{patient}</from>
			</field>
			<field name="author" internal="parent02">
				<from>#{internalId( account, act.participation['author'].role.id)}</from>
				<from>#{internalId( account, trim.act.participation['author'].role.id)}</from>
			</field>
			<field name="enteredBy" internal="string05">
				<from>#{internalId( account, act.participation['dataEnterer'].role.id)}</from>
				<from>#{internalId( account, trim.act.participation['dataEnterer'].role.id)}</from>
			</field>
			<field name="status" internal="string03">
				<from>#{trim.act.statusCode}</from>
			</field>
			<field name="count" internal="long02">
				<from>#{trim.isName['docclin/evn/problem'].act.relationship['submitStatus'].act.observation.values[0].INT.value}</from>
			</field>
			<field name="isSubmitted" internal="string02">
				<from>#{trim.isName['docclin/evn/problem'].act.relationship['submitStatus'].act.observation.values[1].ST.value}</from>
			</field>
		</placeholder>
	</extends>
	<extends path="echr:patient:summary">
		<list name="probsum" visible="never">
			<column name="effectiveTime" internal="date01" format="MM/dd/yyyy">
				<from>#{problem.effectiveTimeLow}</from>
			</column>
			<column name="title" internal="string01">
				<from>#{problem.title}</from>
			</column>
			<column name="status" internal="string02">
				<from>#{problem.status}</from>
			</column>
		</list>
	</extends>
	<extends path="echr:patient:summary:portal">
		<portlet name="probsum" portalColumn="1" sequence="1" title="Problems" page="/five/summaryPortletList.xhtml" query="echr:patient:summary:probsum" visible="true" drilldown=":problems">
			<action name="menu" title="New" page="/five/list.xhtml" visible="true" query="global:problemDocMenu">
				<column name="Problem" internal="string01" instantiate="true" width="40.0" />
			</action>
		</portlet>
	</extends>

	<extends path="echr:patient">
		<menu name="problems" sequence="2" title="Problems" page="/five/bar2.xhtml" visible="true">
			<list name="active" title="Active" page="/five/list.xhtml" visible="true" drilldown=":problem">
				<column name="Date" internal="date01" format="MMM-dd-yyyy" width="8.0">
					<from>#{problem.effectiveTimeLow}</from>
				</column>
				<column name="ActivityTime" internal="date02" format="MMM-dd-yyyy" width="8.0">
					<from>#{problem.availabilityTime}</from>
				</column>
				<column name="Problem" internal="string01" reference="true" width="45.0">
					<from>#{problem.title}</from>
				</column>
				<column name="Code" internal="string06" reference="true" width="15.0">
					<from>#{problem.code}</from>
				</column>
				<column name="Source" internal="string02" width="10.0">
					<from>#{problem.author.lastName}</from>
					<from>#{problem.enteredBy}</from>
					<output>
						<a title="#{problem.author.lastName}#{problem.enteredBy}">#{processSource(string02)}</a>
					</output>
				</column>
				<column name="Status" internal="string03" width="10.0">
					<from>#{problem.status}</from>
				</column>
				<action name="menu" title="New" page="/five/list.xhtml" visible="true" query="global:problemDocMenu">
					<column name="Problem" internal="string01" instantiate="true" width="40.0" />
				</action>
			</list>
			<list name="inactive" title="Inactive" page="/five/list.xhtml" visible="true" drilldown=":problem">
				<column name="Date" internal="date01" format="MMM-dd-yyyy" width="8.0">
					<from>#{problem.effectiveTimeLow}</from>
				</column>
				<column name="ActivityTime" internal="date02" format="MMM-dd-yyyy" width="8.0">
					<from>#{problem.availabilityTime}</from>
				</column>
				<column name="Problem" internal="string01" reference="true" width="45.0">
					<from>#{problem.title}</from>
				</column>
				<column name="Code" internal="string06" reference="true" width="15.0">
					<from>#{problem.code}</from>
				</column>
				<column name="Source" internal="string02" width="10.0">
					<from>#{problem.author.lastName}</from>
					<from>#{problem.enteredBy}</from>
				</column>
				<column name="Status" internal="string03" width="10.0">
					<from>#{problem.status}</from>
				</column>
			</list>
			<list name="nullified" title="Nullified" page="/five/list.xhtml" visible="true" drilldown=":problem">
				<column name="Date" internal="date01" format="MMM-dd-yyyy" width="8.0">
					<from>#{problem.effectiveTimeLow}</from>
				</column>
				<column name="ActivityTime" internal="date02" format="MMM-dd-yyyy" width="8.0">
					<from>#{problem.availabilityTime}</from>
				</column>
				<column name="Problem" internal="string01" reference="true" width="45.0">
					<from>#{problem.title}</from>
				</column>
				<column name="Code" internal="string06" reference="true" width="15.0">
					<from>#{problem.code}</from>
				</column>
				<column name="Source" internal="string02" width="10.0">
					<from>#{problem.author.lastName}</from>
					<from>#{problem.enteredBy}</from>
				</column>
				<column name="Status" internal="string03" width="10.0">
					<from>#{problem.status}</from>
				</column>
			</list>
			<list name="completed" title="Completed" page="/five/list.xhtml" visible="true" drilldown=":problem">
				<column name="Date" internal="date01" format="MMM-dd-yyyy" width="8.0">
					<from>#{problem.effectiveTimeLow}</from>
				</column>
				<column name="ActivityTime" internal="date02" format="MMM-dd-yyyy" width="8.0">
					<from>#{problem.availabilityTime}</from>
				</column>
				<column name="Problem" internal="string01" reference="true" width="45.0">
					<from>#{problem.title}</from>
				</column>
				<column name="Code" internal="string06" reference="true" width="15.0">
					<from>#{problem.code}</from>
				</column>
				<column name="Source" internal="string02" width="10.0">
					<from>#{problem.author.lastName}</from>
					<from>#{problem.enteredBy}</from>
				</column>
				<column name="Status" internal="string03" width="10.0">
					<from>#{problem.status}</from>
				</column>
			</list>
			<list name="all" title="All" page="/five/list.xhtml" visible="true" drilldown=":problem">
				<column name="Date" internal="date01" format="MMM-dd-yyyy" width="8.0">
					<from>#{problem.effectiveTimeLow}</from>
				</column>
				<column name="ActivityTime" internal="date02" format="MMM-dd-yyyy" width="8.0">
					<from>#{problem.availabilityTime}</from>
				</column>
				<column name="Problem" internal="string01" reference="true" width="45.0">
					<from>#{problem.title}</from>
				</column>
				<column name="Code" internal="string06" reference="true" width="15.0">
					<from>#{problem.code}</from>
				</column>
				<column name="Source" internal="string02" width="10.0">
					<from>#{problem.author.lastName}</from>
					<from>#{problem.enteredBy}</from>
				</column>
				<column name="Status" internal="string03" width="10.0">
					<from>#{problem.status}</from>
				</column>
			</list>
		</menu>
	</extends>
	
</application>

=== dubrsl/tolven/org.tolven.onc.applications/app/onc-echr-patient-referral.application.xml
<application xmlns="urn:tolven-org:menuStructure:1.0"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="urn:tolven-org:menuStructure:1.0 http://tolven.org/xsd/menuStructure.xsd">

	<extends path="echr:patient:orders">
		<list name="referralRequests" title="Referral Requests" page="/five/list.xhtml" visible="true" drilldown=":referralRequest">
			<column name="Date" internal="date01" format="MMM-dd-yyyy" width="15.0">
				<from>#{referralRequest.date}</from>
			</column>
			<column name="Name" internal="string01" width="30.0" reference="true">
				<from>#{referralRequest.serviceName}</from>
			</column>
			<column name="Status" internal="string02" width="30.0">
				<from>#{referralRequest.status}</from>
			</column>
			<column width="15.0" internal="string03" name="Performer">
				<from>#{referralRequest.author.lastName}</from>
				<from>#{referralRequest.enteredBy}</from>
			</column>
			<action name="menu" title="New" page="/five/list.xhtml" visible="true" query="global:referralRequestDocMenu">
				<column name="Title" internal="string01" instantiate="true" width="40.0" />
			</action>
		</list>
	</extends>
</application>

=== dubrsl/tolven/trunk/org.tolven.jmetertests/data/org.tolven.prototype.applications/applications/echr-favorites.application.xml
<application xmlns="urn:tolven-org:menuStructure:1.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
	xsi:schemaLocation="urn:tolven-org:menuStructure:1.0 http://tolven.org/xsd/menuStructure.xsd">
	<property accountType="echr" name="favoritePath">echr:admin:lists:accountLists,echr:assigned:lists:personalLists</property>
	<property accountType="echr"  name="favoritePrefPath">favorite.preferences</property>
	<!-- Add Account list category to admin menu -->
	<extends path="echr:admin">
		<menu name="lists" title="Lists" page="/five/bar2.xhtml" visible="true"/>
	</extends>
	<!-- Add Account favorites list Account list tab -->
	<extends path="echr:admin:lists" >
		<list name="accountLists" title="AccountLists" page="/five/list.xhtml" visible="true" drilldown="echr:accountList">
			<column name="Title" internal="string01" width="15.0">
				<from>#{accountList.name}</from>
			</column>
			<column name="DisplayName" internal="string02" width="20.0" reference="true">
				<from>#{accountList.displayName}</from>
			</column>
			<column name="Type" internal="string04" width="20.0">
				<from>#{accountList.type}</from>
			</column>
			<action name="menu" title="New" page="/five/list.xhtml" visible="true" query="global:accountListsMenu">
				<column name="Name" internal="string01" instantiate="true" width="40.0" />
			</action>
		</list>
	</extends>
	<!-- Add Personal list category to assigned (staff) menu -->
	<extends path="echr:assigned">
		<menu name="lists" title="Lists" page="/five/bar2.xhtml" visible="true"/>
	</extends>
	<!-- Add Personal favorites list to assigned (staff) menu -->
	<extends path="echr:assigned:lists">	
		<list name="personalLists" title="PersonalLists" page="/five/list.xhtml" visible="true" drilldown="echr:personalList">
			<column name="Title" internal="string01" width="15.0">
				<from>#{personalList.name}</from>
			</column>
			<column name="DisplayName" internal="string02" width="20.0" reference="true">
				<from>#{personalList.displayName}</from>
			</column>
			<column name="Type" internal="string04" width="20.0">
				<from>#{personalList.type}</from>
			</column>
			<action name="menu" title="New" page="/five/list.xhtml" visible="true" query="global:personalListsMenu">
				<column name="Name" internal="string01" instantiate="true" width="40.0" />
			</action>
		</list>
	</extends>
	<!-- Account favorites list placeholder -->
	<extends path="echr" >
		<placeholder name="accountList" title="AccountList" eventInstance="echr:admin:wip" page="/five/location.xhtml" heading="/five/locationLink.xhtml">
			<field name="name" internal="string01">
				<from>#{act.title.ST.value}</from>
			</field>
			<field name="displayName" internal="string02">
				<from>#{act.relationship['displayName'].act.title.ST.value}</from>
			</field>
			<field name="type" internal="string04">
				<from>#{act.relationship['type'].act.title.ST.value}</from>
			</field>
			<list name="favorites" title="Favorites" page="/five/list.xhtml" visible="true" drilldown=":favorite">
				<column name="Name" internal="string01" width="40.0">
					<from>#{favorite.name}</from>
				</column>
				<column name="Original" visible="false" internal="string02">
					<from>#{favorite.original}</from>
				</column>
			</list>
			<placeholder name="favorite" title="Favorite" eventInstance="echr:admin:wip" page="/five/location.xhtml" heading="/five/locationLink.xhtml">
				<field name="name" internal="string01">
					<from>#{act.title.ST.value}</from>
				</field>
				<field name="original" internal="string02">
					<from>#{act.relationship['path'].act.title.ST.value}</from>
				</field>
				<field name="parent" internal="parent01">
					<from>#{accountList}</from>
				</field>
			</placeholder>
		</placeholder>
	</extends>
	<!-- Personal favorites list placeholder -->
	<extends path="echr:assigned">
		<placeholder name="personalList" title="Personal List" eventInstance="echr:admin:wip" page="/five/location.xhtml" heading="/five/locationLink.xhtml">
			<field name="name" internal="string01">
				<from>#{act.title.ST.value}</from>
			</field>
			<field name="displayName" internal="string02">
				<from>#{act.relationship['displayName'].act.title.ST.value}</from>
			</field>
			<field name="type" internal="string04">
				<from>#{act.relationship['type'].act.title.ST.value}</from>
			</field>
			<list name="favorites" title="Favorites" page="/five/list.xhtml" visible="true" drilldown=":personalFavorite">
				<column name="Name" internal="string01" width="40.0">
					<from>#{favorite.name}</from>
				</column>
				<column name="Original" visible="false" internal="string02">
					<from>#{favorite.original}</from>
				</column>
			</list>
			<placeholder name="pfavorite" title="Favorite" eventInstance="echr:admin:wip" page="/five/location.xhtml" heading="/five/locationLink.xhtml">
				<field name="name" internal="string01">
					<from>#{act.title.ST.value}</from>
				</field>
				<field name="original" internal="string02">
					<from>#{act.relationship['path'].act.title.ST.value}</from>
				</field>
				<field name="parent" internal="parent01">
					<from>#{accountList}</from>
				</field>
			</placeholder>
		</placeholder>
	</extends>

</application>

=== dubrsl/tolven/trunk/org.tolven.prototype.applications/app/echr-report.application.xml
<application xmlns="urn:tolven-org:menuStructure:1.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
	xsi:schemaLocation="urn:tolven-org:menuStructure:1.0 http://tolven.org/xsd/menuStructure.xsd">
	<extends path="echr">
		<menu name="reports" title="Reports" page="/five/bar1.xhtml" visible="true">
		<list name="all" title="My Reports" page="/five/reportLink.xhtml" visible="true" drilldown="echr:reports">
				
				<action name="menu" title="New" page="/five/reportLink.xhtml" visible="true" query="global:reportMenu">
					<column name="Report" internal="string01" instantiate="true" width="40.0"/>
				</action>
			</list>
			<instance name="wip" title="New" page="/wizard/wizard.xhtml" heading="/five/wipLink.xhtml"/>
		</menu>
	</extends>
	<extends path="echr">
		<placeholder name="report" title="Report" page="/wizard/wizard.xhtml" heading="/five/reportLink.xhtml">
			
		</placeholder>
	</extends>
</application>
